import type { Catalog } from "./index";

export const financialCatalogs: Record<string, Catalog> = {
  "pci-dss": {
    version: "v4.0",
    sourceUrl: "https://www.pcisecuritystandards.org/standards/pci-dss/",
    controls: [
      { controlId: "Req 1", title: "Install and Maintain Network Security Controls", description: "Install and maintain network security controls to protect the cardholder data environment.", domain: "Build and Maintain a Secure Network" },
      { controlId: "1.1", title: "Network Security Control Processes", description: "Define and maintain processes for installing and maintaining network security controls.", domain: "Build and Maintain a Secure Network" },
      { controlId: "1.2", title: "Network Diagrams and Data Flows", description: "Maintain accurate network diagrams and data flow descriptions for the cardholder data environment.", domain: "Build and Maintain a Secure Network" },
      { controlId: "1.3", title: "Network Security Controls Configuration", description: "Configure network security controls to deny all traffic by default and allow only necessary traffic.", domain: "Build and Maintain a Secure Network" },
      { controlId: "1.4", title: "Control of Non-Console Access", description: "Control connections between the cardholder data environment and untrusted networks.", domain: "Build and Maintain a Secure Network" },
      { controlId: "1.5", title: "Intrusion Detection and Prevention", description: "Implement intrusion detection and prevention techniques to detect and prevent malicious traffic.", domain: "Build and Maintain a Secure Network" },
      { controlId: "Req 2", title: "Apply Secure Configurations to All System Components", description: "Apply secure configurations to all system components and remove defaults and unnecessary functionality.", domain: "Build and Maintain a Secure Network" },
      { controlId: "2.1", title: "Secure Configuration Standards", description: "Establish and maintain configuration standards covering all system components.", domain: "Build and Maintain a Secure Network" },
      { controlId: "2.2", title: "System Inventory", description: "Maintain a complete inventory of system components and remove outdated components.", domain: "Build and Maintain a Secure Network" },
      { controlId: "2.3", title: "Remove Vendor Defaults", description: "Change vendor defaults, including passwords, and remove unnecessary accounts and services.", domain: "Build and Maintain a Secure Network" },
      { controlId: "2.4", title: "Non-Console Administrative Access", description: "Restrict administrative access to authorized personnel only.", domain: "Build and Maintain a Secure Network" },
      { controlId: "Req 3", title: "Protect Stored Account Data", description: "Protect stored cardholder data through encryption, masking, and minimization.", domain: "Protect Cardholder Data" },
      { controlId: "3.1", title: "Data Retention and Disposal", description: "Minimize storage of cardholder data and securely delete data when no longer needed.", domain: "Protect Cardholder Data" },
      { controlId: "3.2", title: "Primary Account Number Masking", description: "Mask the primary account number when displayed.", domain: "Protect Cardholder Data" },
      { controlId: "3.3", title: "Sensitive Authentication Data", description: "Do not store sensitive authentication data after authorization, including card verification codes and magnetic stripe data.", domain: "Protect Cardholder Data" },
      { controlId: "3.4", title: "Cryptographic Protection of PAN", description: "Render PAN unreadable wherever stored using strong cryptography.", domain: "Protect Cardholder Data" },
      { controlId: "3.5", title: "Keys and Passwords for Cardholder Data", description: "Document and manage cryptographic keys and passwords protecting stored account data.", domain: "Protect Cardholder Data" },
      { controlId: "Req 4", title: "Protect Cardholder Data with Strong Cryptography During Transmission", description: "Protect cardholder data with strong cryptography during transmission over open, public networks.", domain: "Protect Cardholder Data" },
      { controlId: "4.1", title: "Encryption of PAN During Transmission", description: "Use strong cryptography and security protocols to safeguard PAN during transmission.", domain: "Protect Cardholder Data" },
      { controlId: "4.2", title: "Disable Insecure Protocols", description: "Configure and use only secure network protocols for cardholder data transmission.", domain: "Protect Cardholder Data" },
      { controlId: "Req 5", title: "Protect All Systems and Networks from Malicious Software", description: "Protect all systems and networks from malicious software and update mechanisms regularly.", domain: "Maintain a Vulnerability Management Program" },
      { controlId: "5.1", title: "Anti-Malware Protection", description: "Deploy and maintain anti-malware software on all systems, including mobile and removable media.", domain: "Maintain a Vulnerability Management Program" },
      { controlId: "5.2", title: "Anti-Malware Updates and Detection", description: "Keep anti-malware mechanisms updated, perform periodic scans, and address detected threats.", domain: "Maintain a Vulnerability Management Program" },
      { controlId: "5.3", title: "Anti-Malware Mechanisms on Mobile Devices", description: "Deploy anti-malware mechanisms on mobile devices that meet the entity's risk criteria.", domain: "Maintain a Vulnerability Management Program" },
      { controlId: "5.4", title: "Anti-Phishing and Anti-Scripting", description: "Protect against phishing, web-based attacks, and malicious scripts in payment environments.", domain: "Maintain a Vulnerability Management Program" },
      { controlId: "Req 6", title: "Develop and Maintain Secure Systems and Software", description: "Develop and maintain secure systems and software, including applying security patches promptly.", domain: "Maintain a Vulnerability Management Program" },
      { controlId: "6.1", title: "Secure Software Development", description: "Secure the software development lifecycle and protect against known vulnerabilities and coding flaws.", domain: "Maintain a Vulnerability Management Program" },
      { controlId: "6.2", title: "Custom Application Security Testing", description: "Apply application security testing against custom software for vulnerabilities.", domain: "Maintain a Vulnerability Management Program" },
      { controlId: "6.3", title: "Vulnerability and Patch Management", description: "Identify and address security vulnerabilities, installing critical patches within one month.", domain: "Maintain a Vulnerability Management Program" },
      { controlId: "6.4", title: "Secure Changes", description: "Implement security considerations for application development, changes, and administration.", domain: "Maintain a Vulnerability Management Program" },
      { controlId: "Req 7", title: "Restrict Access to Cardholder Data by Business Need to Know", description: "Restrict access to cardholder data to those whose job requires it.", domain: "Implement Strong Access Control Measures" },
      { controlId: "7.1", title: "Restrict Access by Business Need to Know", description: "Define and enforce access restrictions based on business need to know.", domain: "Implement Strong Access Control Measures" },
      { controlId: "7.2", title: "Role-Based Access", description: "Assign access to cardholder data based on roles and responsibilities.", domain: "Implement Strong Access Control Measures" },
      { controlId: "7.3", title: "Review and Adjust Access", description: "Review and adjust access rights at least quarterly.", domain: "Implement Strong Access Control Measures" },
      { controlId: "Req 8", title: "Identify Users and Authenticate Access", description: "Identify users and authenticate access to system components with strong authentication.", domain: "Implement Strong Access Control Measures" },
      { controlId: "8.1", title: "Unique User Identification", description: "Assign a unique ID to each person with access to system components.", domain: "Implement Strong Access Control Measures" },
      { controlId: "8.2", title: "Strong Authentication", description: "Authenticate users with passwords, passphrases, cryptographic devices, or biometrics as appropriate.", domain: "Implement Strong Access Control Measures" },
      { controlId: "8.3", title: "Multifactor Authentication", description: "Use multifactor authentication for non-console administrative access and remote network access.", domain: "Implement Strong Access Control Measures" },
      { controlId: "8.4", title: "Account Lockout and Password Management", description: "Manage passwords, implement lockouts after failed attempts, and secure authentication data.", domain: "Implement Strong Access Control Measures" },
      { controlId: "8.5", title: "Session and Access Management", description: "Manage user sessions, restrict access to authentication data, and verify the identity of users.", domain: "Implement Strong Access Control Measures" },
      { controlId: "Req 9", title: "Restrict Physical Access to Cardholder Data", description: "Restrict physical access to cardholder data and facilities where cardholder data is processed or stored.", domain: "Implement Strong Access Control Measures" },
      { controlId: "9.1", title: "Physical Access Controls", description: "Control physical access to facilities and systems storing or processing cardholder data.", domain: "Implement Strong Access Control Measures" },
      { controlId: "9.2", title: "Physical Access for Onsite Personnel", description: "Issue badges and manage access of onsite personnel, and revoke access upon termination.", domain: "Implement Strong Access Control Measures" },
      { controlId: "9.3", title: "Visitor Management", description: "Control and log visitor access and visually inspect for unauthorized devices.", domain: "Implement Strong Access Control Measures" },
      { controlId: "9.4", title: "Media Protection", description: "Physically secure media and devices containing cardholder data and track inventory.", domain: "Implement Strong Access Control Measures" },
      { controlId: "9.5", title: "Media Destruction", description: "Destroy hard copy and electronic media containing cardholder data when no longer needed.", domain: "Implement Strong Access Control Measures" },
      { controlId: "Req 10", title: "Log and Monitor All Access to System Components and Cardholder Data", description: "Log and monitor all access to system components and cardholder data.", domain: "Regularly Monitor and Test Networks" },
      { controlId: "10.1", title: "Audit Logs", description: "Implement audit logs capturing all individual user access to cardholder data.", domain: "Regularly Monitor and Test Networks" },
      { controlId: "10.2", title: "Log Retention and Protection", description: "Protect audit logs from modification and retain them for at least 12 months.", domain: "Regularly Monitor and Test Networks" },
      { controlId: "10.3", title: "Log Monitoring and Alerting", description: "Review logs, monitor activity, and alert on suspicious events, including all large-scale access anomalies.", domain: "Regularly Monitor and Test Networks" },
      { controlId: "10.4", title: "Clock Synchronization", description: "Synchronize clocks across systems to enable correlation of audit logs.", domain: "Regularly Monitor and Test Networks" },
      { controlId: "10.5", title: "Audit Log Security", description: "Secure audit logs and protect against unauthorized modification, deletion, and generation.", domain: "Regularly Monitor and Test Networks" },
      { controlId: "Req 11", title: "Test Security of Systems and Networks Regularly", description: "Test the security of systems and networks regularly to detect and address vulnerabilities.", domain: "Regularly Monitor and Test Networks" },
      { controlId: "11.1", title: "Wireless and Internal Vulnerability Scanning", description: "Run internal and external vulnerability scans at least quarterly and after significant changes.", domain: "Regularly Monitor and Test Networks" },
      { controlId: "11.2", title: "Penetration Testing", description: "Perform internal and external penetration testing at least annually and after significant changes.", domain: "Regularly Monitor and Test Networks" },
      { controlId: "11.3", title: "Change Detection", description: "Deploy a change detection mechanism to alert personnel to unauthorized modification of critical files.", domain: "Regularly Monitor and Test Networks" },
      { controlId: "11.4", title: "Unauthorized Wireless Access Detection", description: "Monitor for unauthorized wireless access points and maintain an inventory of authorized ones.", domain: "Regularly Monitor and Test Networks" },
      { controlId: "11.5", title: "Network and Security Control Monitoring", description: "Monitor for evidence of unauthorized network and security control changes.", domain: "Regularly Monitor and Test Networks" },
      { controlId: "Req 12", title: "Support Information Security with Organizational Policies and Programs", description: "Support information security with organizational policies, programs, and risk management.", domain: "Maintain an Information Security Policy" },
      { controlId: "12.1", title: "Information Security Policy", description: "Establish, publish, maintain, and disseminate an information security policy.", domain: "Maintain an Information Security Policy" },
      { controlId: "12.2", title: "Risk Assessment", description: "Conduct risk assessments at least annually and after significant changes.", domain: "Maintain an Information Security Policy" },
      { controlId: "12.3", title: "Roles and Responsibilities", description: "Define and communicate information security roles and responsibilities.", domain: "Maintain an Information Security Policy" },
      { controlId: "12.4", title: "Usage Policies", description: "Define and enforce policies for the acceptable use of end-user technologies.", domain: "Maintain an Information Security Policy" },
      { controlId: "12.5", title: "Personnel Management", description: "Screen personnel and provide security awareness training, including on phishing.", domain: "Maintain an Information Security Policy" },
      { controlId: "12.6", title: "Incident Response", description: "Implement an incident response plan with defined roles and preparation for compromised payment devices.", domain: "Maintain an Information Security Policy" },
      { controlId: "12.7", title: "Service Provider Management", description: "Manage service providers by identifying, monitoring, and confirming they support compliance.", domain: "Maintain an Information Security Policy" },
      { controlId: "12.8", title: "Security Awareness Program", description: "Maintain a security awareness program addressing risks, including phishing and social engineering.", domain: "Maintain an Information Security Policy" },
      { controlId: "12.9", title: "Security Monitoring and Reporting", description: "Monitor security controls and report security incidents to senior management.", domain: "Maintain an Information Security Policy" },
    ],
  },

  sox: {
    version: "2002",
    sourceUrl: "https://www.pcaobus.org/oversight/standards/auditing-standards/details/AS2201",
    controls: [
      { controlId: "ITGC-1", title: "Access Management", description: "Establish user access controls so that only authorized personnel access systems supporting financial reporting.", domain: "IT General Controls" },
      { controlId: "ITGC-2", title: "User Access Reviews", description: "Periodically review and validate that user access rights are appropriate and current.", domain: "IT General Controls" },
      { controlId: "ITGC-3", title: "Privileged Access Control", description: "Restrict, monitor, and manage administrative and privileged access to systems.", domain: "IT General Controls" },
      { controlId: "ITGC-4", title: "Segregation of Duties", description: "Separate incompatible duties across IT and financial processes to prevent errors and fraud.", domain: "IT General Controls" },
      { controlId: "ITGC-5", title: "Change Management", description: "Formally authorize, test, approve, and document changes to systems supporting financial reporting.", domain: "IT General Controls" },
      { controlId: "ITGC-6", title: "Program and Data Migration Controls", description: "Control the migration of programs and data, including configuration and table changes.", domain: "IT General Controls" },
      { controlId: "ITGC-7", title: "Backup and Recovery", description: "Maintain and test backups of systems and data supporting financial reporting.", domain: "IT General Controls" },
      { controlId: "ITGC-8", title: "Disaster Recovery and Business Continuity", description: "Maintain plans to recover financial reporting systems after a disruption.", domain: "IT General Controls" },
      { controlId: "ITGC-9", title: "Incident Management", description: "Identify, respond to, and document IT incidents that may affect financial reporting.", domain: "IT General Controls" },
      { controlId: "ITGC-10", title: "System Operations", description: "Define and operate documented procedures for running systems supporting financial reporting.", domain: "IT General Controls" },
      { controlId: "ITGC-11", title: "Job Scheduling", description: "Manage automated job scheduling and resolve job failures in a timely manner.", domain: "IT General Controls" },
      { controlId: "ITGC-12", title: "Database Security", description: "Secure databases supporting financial reporting, including configuration and access.", domain: "IT General Controls" },
      { controlId: "ITGC-13", title: "Application Security", description: "Configure financial applications securely and limit access to transaction functions.", domain: "IT General Controls" },
      { controlId: "ITGC-14", title: "Interface and Data Feeds", description: "Control interfaces and data feeds between financial and supporting systems.", domain: "IT General Controls" },
      { controlId: "ITGC-15", title: "Data Center and Physical Security", description: "Protect the physical facilities hosting financial reporting systems.", domain: "IT General Controls" },
      { controlId: "ITGC-16", title: "Vendor and Service Provider Oversight", description: "Assess and monitor third-party providers that support financial reporting processes.", domain: "IT General Controls" },
      { controlId: "IC-1", title: "Internal Control Over Financial Reporting", description: "Maintain effective internal controls over financial reporting, including IT general controls.", domain: "Internal Control" },
      { controlId: "IC-2", title: "Control Documentation", description: "Document controls, including risk and control matrices, to support the assessment.", domain: "Internal Control" },
      { controlId: "IC-3", title: "Management Testing of Controls", description: "Test the operating effectiveness of controls related to financial reporting.", domain: "Internal Control" },
      { controlId: "IC-4", title: "Control Deficiency Remediation", description: "Identify, evaluate, and remediate control deficiencies, including significant deficiencies and material weaknesses.", domain: "Internal Control" },
    ],
  },

  glba: {
    version: "Safeguards Rule 2023",
    sourceUrl: "https://www.ftc.gov/business-guidance/privacy-security/gramm-leach-bliley-act",
    controls: [
      { controlId: "314.2", title: "Risk Assessment", description: "Assess reasonably foreseeable internal and external risks to customer information at least annually.", domain: "Safeguards Rule" },
      { controlId: "314.4(a)", title: "Written Information Security Program", description: "Develop, implement, and maintain a comprehensive written information security program.", domain: "Safeguards Rule" },
      { controlId: "314.4(b)", title: "Program Coordinator", description: "Designate an employee to coordinate the information security program.", domain: "Safeguards Rule" },
      { controlId: "314.4(c)", title: "Design and Implementation of Safeguards", description: "Design safeguards for each area of the financial institution covered by the program.", domain: "Safeguards Rule" },
      { controlId: "314.4(d)", title: "Service Provider Oversight", description: "Select and retain service providers that maintain appropriate safeguards and require them to notify of incidents.", domain: "Safeguards Rule" },
      { controlId: "314.4(e)", title: "Program Evaluation and Adjustment", description: "Evaluate and adjust the program in light of changes in technology, operations, and new risks.", domain: "Safeguards Rule" },
      { controlId: "314.4(f)(1)", title: "Employee Training", description: "Train staff on the security program and its implementation.", domain: "Safeguards Rule" },
      { controlId: "314.4(f)(2)", title: "Information Security Awareness", description: "Maintain awareness and address personnel changes, training, and monitoring of sensitive information.", domain: "Safeguards Rule" },
      { controlId: "314.4(f)(3)", title: "Access Control", description: "Limit access to customer information to authorized personnel with a legitimate business need.", domain: "Safeguards Rule" },
      { controlId: "314.4(f)(4)", title: "Authentication Controls", description: "Use appropriate authentication controls for access to customer information.", domain: "Safeguards Rule" },
      { controlId: "314.4(f)(5)", title: "Data Encryption", description: "Encrypt customer information in transit and at rest where appropriate.", domain: "Safeguards Rule" },
      { controlId: "314.4(f)(6)", title: "System and Network Monitoring", description: "Monitor systems and networks for unauthorized access, including via intrusion detection systems.", domain: "Safeguards Rule" },
      { controlId: "314.4(f)(7)", title: "Secure Disposal of Data", description: "Securely dispose of customer information no longer needed for business or legal purposes.", domain: "Safeguards Rule" },
      { controlId: "314.4(f)(8)", title: "Change Management", description: "Manage changes to systems that affect customer information.", domain: "Safeguards Rule" },
      { controlId: "314.4(f)(9)", title: "Incident Response", description: "Develop and implement an incident response plan for detected unauthorized access to customer information.", domain: "Safeguards Rule" },
      { controlId: "GLBA Privacy Rule", title: "Privacy Notice", description: "Provide clear and conspicuous notices explaining information collection, sharing, and opt-out rights.", domain: "Privacy Rule" },
      { controlId: "GLBA Opt-Out", title: "Opt-Out Rights", description: "Provide consumers the ability to opt out of sharing nonpublic personal information with nonaffiliated third parties.", domain: "Privacy Rule" },
    ],
  },

  dora: {
    version: "2022/2554",
    sourceUrl: "https://digital-finance-platform.ec.europa.eu/regulatory-activities/dora",
    controls: [
      { controlId: "Art. 5", title: "ICT Risk Management Framework", description: "Establish a sound and comprehensive ICT risk management framework documented in internal policies.", domain: "ICT Risk Management" },
      { controlId: "Art. 6", title: "Governance and Organisation", description: "Allocate roles and responsibilities for ICT risk management and assign reporting lines to management.", domain: "ICT Risk Management" },
      { controlId: "Art. 7", title: "ICT Risk Management System", description: "Use an ICT risk management system based on the identification and assessment of ICT risk.", domain: "ICT Risk Management" },
      { controlId: "Art. 8", title: "Identification", description: "Identify and record all ICT assets, including business functions, processes, and dependencies.", domain: "ICT Risk Management" },
      { controlId: "Art. 9", title: "Protection and Prevention", description: "Implement ICT protection and prevention tools, policies, and procedures to ensure security of networks and data.", domain: "ICT Risk Management" },
      { controlId: "Art. 10", title: "Detection", description: "Detect anomalous activities and implement measures to alert on ICT risk incidents and anomalies.", domain: "ICT Risk Management" },
      { controlId: "Art. 11", title: "Response and Recovery", description: "Implement response and recovery plans to maintain operations and restore affected systems.", domain: "ICT Risk Management" },
      { controlId: "Art. 12", title: "Backup Policy and Procedures", description: "Establish backup policies and restoration and recovery procedures tested at regular intervals.", domain: "ICT Risk Management" },
      { controlId: "Art. 13", title: "Learning and Evolution", description: "Conduct post-incident reviews and use lessons learned to continuously improve ICT security capabilities.", domain: "ICT Risk Management" },
      { controlId: "Art. 14", title: "Communication", description: "Communicate ICT risk management outcomes and lessons learned to relevant internal and external parties.", domain: "ICT Risk Management" },
      { controlId: "Art. 17", title: "ICT-Related Incident Classification", description: "Classify ICT-related incidents and report major incidents to competent authorities.", domain: "Incident Reporting" },
      { controlId: "Art. 19", title: "Major Incident Reporting", description: "Notify competent authorities of major ICT-related incidents, including the response and impact.", domain: "Incident Reporting" },
      { controlId: "Art. 20", title: "Communication of Major Incidents to Clients", description: "Inform clients about major ICT-related incidents that have a significant impact on their financial interests.", domain: "Incident Reporting" },
      { controlId: "Art. 24", title: "ICT Resilience Testing", description: "Establish a programme of digital operational resilience testing, including vulnerability assessments and penetration testing.", domain: "Resilience Testing" },
      { controlId: "Art. 25", title: "Testing of ICT Tools and Systems", description: "Test ICT tools, systems, and processes for resilience at least annually.", domain: "Resilience Testing" },
      { controlId: "Art. 26", title: "Threat-Led Penetration Testing", description: "Perform threat-led penetration testing at least every three years with the involvement of independent testers.", domain: "Resilience Testing" },
      { controlId: "Art. 28", title: "Contractual Agreements with ICT Third-Party Providers", description: "Conclude written agreements covering full lifecycle management, exit strategies, and monitoring of subcontractors.", domain: "Third-Party Risk" },
      { controlId: "Art. 30", title: "Register of Information", description: "Maintain a register of information on all contractual arrangements with ICT third-party service providers.", domain: "Third-Party Risk" },
      { controlId: "Art. 32", title: "Concentration Risk", description: "Identify and manage concentration risk from ICT third-party service providers, including subcontracting.", domain: "Third-Party Risk" },
      { controlId: "Art. 45", title: "Information Sharing Arrangements", description: "Exchange cyber threat information and intelligence among trusted entities under security arrangements.", domain: "Information Sharing" },
    ],
  },

  "soc-1": {
    version: "SSAE 18",
    sourceUrl: "https://www.aicpa-cima.com/topic/audit-assurance/audit-and-assurance-greater-than-soc-2",
    controls: [
      { controlId: "CT-1", title: "Control Environment", description: "Establish a control environment including integrity, ethical values, and board oversight.", domain: "Trust Services Criteria" },
      { controlId: "CT-2", title: "Risk Assessment", description: "Identify and analyze risks to achieving financial reporting objectives.", domain: "Trust Services Criteria" },
      { controlId: "CT-3", title: "Control Activities", description: "Select and implement control activities that address identified risks.", domain: "Trust Services Criteria" },
      { controlId: "CT-4", title: "Information and Communication", description: "Obtain, generate, and communicate information supporting internal control over financial reporting.", domain: "Trust Services Criteria" },
      { controlId: "CT-5", title: "Monitoring Activities", description: "Select, develop, and perform ongoing evaluations of controls and remediate deficiencies.", domain: "Trust Services Criteria" },
      { controlId: "ICFR-1", title: "Transaction Processing Controls", description: "Design controls over the initiation, authorization, recording, processing, and reporting of transactions.", domain: "ICFR Controls" },
      { controlId: "ICFR-2", title: "System Access Controls", description: "Restrict access to systems and data relevant to financial reporting to authorized personnel.", domain: "ICFR Controls" },
      { controlId: "ICFR-3", title: "Change Management Controls", description: "Control changes to software, configurations, and data supporting financial reporting.", domain: "ICFR Controls" },
      { controlId: "ICFR-4", title: "Segregation of Duties", description: "Separate duties and incompatible functions across the financial reporting process.", domain: "ICFR Controls" },
      { controlId: "ICFR-5", title: "Data Integrity Controls", description: "Ensure the completeness, accuracy, and validity of data supporting financial reporting.", domain: "ICFR Controls" },
      { controlId: "ICFR-6", title: "Backup and Recovery Controls", description: "Maintain and test backup and recovery processes for financial reporting systems.", domain: "ICFR Controls" },
      { controlId: "ICFR-7", title: "System Monitoring", description: "Monitor system activity and respond to exceptions and anomalies affecting financial reporting.", domain: "ICFR Controls" },
      { controlId: "ICFR-8", title: "Incident Management", description: "Detect, respond to, and report incidents that could affect financial reporting.", domain: "ICFR Controls" },
      { controlId: "ICFR-9", title: "Service Organization Controls", description: "Document the controls, including complementary user entity controls, relied upon by user organizations.", domain: "ICFR Controls" },
    ],
  },
};
