import type { Catalog } from "./index";

export const healthcareCatalogs: Record<string, Catalog> = {
  hipaa: {
    version: "Security Rule",
    sourceUrl: "https://www.ecfr.gov/current/title-45/subtitle-A/subchapter-C/part-164/subpart-C",
    controls: [
      { controlId: "164.308(a)(1)", title: "Security Management Process", description: "Implement policies and procedures to prevent, detect, contain, and correct security violations.", domain: "Administrative Safeguards" },
      { controlId: "164.308(a)(2)", title: "Security Responsibilities", description: "Assign security responsibility to a specific person or role responsible for developing and implementing security policies.", domain: "Administrative Safeguards" },
      { controlId: "164.308(a)(3)(ii)(A)", title: "Workforce Security: Authorization and Supervision", description: "Implement procedures to authorize and supervise workforce members who work with ePHI.", domain: "Administrative Safeguards" },
      { controlId: "164.308(a)(3)(ii)(B)", title: "Workforce Clearance Procedure", description: "Implement procedures to determine that access to ePHI is appropriate and terminated where necessary.", domain: "Administrative Safeguards" },
      { controlId: "164.308(a)(4)", title: "Information Access Management", description: "Implement policies and procedures for authorizing access to ePHI consistent with the Privacy Rule.", domain: "Administrative Safeguards" },
      { controlId: "164.308(a)(5)(ii)(A)", title: "Security Awareness and Training", description: "Provide security awareness training to all workforce members, including updates on security reminders.", domain: "Administrative Safeguards" },
      { controlId: "164.308(a)(5)(ii)(B)", title: "Security Reminders", description: "Protect against malicious software by implementing periodic security reminders to workforce members.", domain: "Administrative Safeguards" },
      { controlId: "164.308(a)(6)", title: "Security Incident Procedures", description: "Implement policies and procedures to address security incidents, including response and reporting.", domain: "Administrative Safeguards" },
      { controlId: "164.308(a)(7)", title: "Contingency Plan", description: "Establish policies and procedures for responding to emergencies that damage systems containing ePHI.", domain: "Administrative Safeguards" },
      { controlId: "164.308(a)(7)(ii)(E)", title: "Testing and Revision Procedures", description: "Establish procedures to test and revise contingency plans on a periodic basis.", domain: "Administrative Safeguards" },
      { controlId: "164.308(a)(8)", title: "Evaluation", description: "Perform a periodic technical and nontechnical evaluation in response to changes affecting ePHI security.", domain: "Administrative Safeguards" },
      { controlId: "164.308(b)(1)", title: "Business Associate Contracts", description: "Obtain satisfactory assurances from business associates that they will appropriately safeguard ePHI.", domain: "Administrative Safeguards" },
      { controlId: "164.310(a)(1)", title: "Facility Access Controls", description: "Implement policies to limit physical access to facilities while ensuring authorized access is permitted.", domain: "Physical Safeguards" },
      { controlId: "164.310(a)(2)(i)", title: "Contingency Operations", description: "Establish procedures that allow facility access in support of restoration of lost data.", domain: "Physical Safeguards" },
      { controlId: "164.310(b)", title: "Workstation Use", description: "Implement policies specifying the proper functions and physical attributes of workstations that access ePHI.", domain: "Physical Safeguards" },
      { controlId: "164.310(c)", title: "Workstation Security", description: "Implement physical safeguards for workstations that access ePHI.", domain: "Physical Safeguards" },
      { controlId: "164.310(d)(1)", title: "Device and Media Controls", description: "Implement policies and procedures governing the receipt and removal of hardware and electronic media with ePHI.", domain: "Physical Safeguards" },
      { controlId: "164.310(d)(2)(i)", title: "Disposal", description: "Implement policies to address the final disposition of ePHI and the hardware or media on which it is stored.", domain: "Physical Safeguards" },
      { controlId: "164.310(d)(2)(ii)", title: "Media Re-Use", description: "Implement procedures for the removal and clearing of ePHI from electronic media before reuse.", domain: "Physical Safeguards" },
      { controlId: "164.312(a)(1)", title: "Access Control", description: "Implement technical policies for electronic information systems that maintain ePHI to allow access only to those granted access.", domain: "Technical Safeguards" },
      { controlId: "164.312(a)(2)(i)", title: "Unique User Identification", description: "Assign a unique name or number for identifying and tracking user identity for access to ePHI.", domain: "Technical Safeguards" },
      { controlId: "164.312(a)(2)(ii)", title: "Emergency Access Procedure", description: "Establish procedures for obtaining necessary ePHI during an emergency.", domain: "Technical Safeguards" },
      { controlId: "164.312(a)(2)(iii)", title: "Automatic Logoff", description: "Implement electronic procedures that terminate an electronic session after a predetermined time of inactivity.", domain: "Technical Safeguards" },
      { controlId: "164.312(a)(2)(iv)", title: "Encryption and Decryption", description: "Implement a mechanism to encrypt and decrypt ePHI.", domain: "Technical Safeguards" },
      { controlId: "164.312(b)", title: "Audit Controls", description: "Implement hardware, software, and procedural mechanisms to record and examine activity in systems containing ePHI.", domain: "Technical Safeguards" },
      { controlId: "164.312(c)(1)", title: "Integrity Controls", description: "Implement policies and procedures to protect ePHI from improper alteration or destruction.", domain: "Technical Safeguards" },
      { controlId: "164.312(e)(1)", title: "Transmission Security", description: "Implement technical security measures to guard against unauthorized access to ePHI transmitted over a network.", domain: "Technical Safeguards" },
      { controlId: "164.312(e)(2)(i)", title: "Integrity Controls", description: "Implement security measures to ensure electronically transmitted ePHI is not improperly modified.", domain: "Technical Safeguards" },
      { controlId: "164.312(e)(2)(ii)", title: "Encryption in Transit", description: "Implement a mechanism to encrypt ePHI whenever deemed appropriate for transmission.", domain: "Technical Safeguards" },
      { controlId: "Privacy Rule", title: "Privacy Rule Safeguards", description: "Comply with use and disclosure limits, minimum necessary requirements, and individual rights for protected health information.", domain: "Privacy Rule" },
      { controlId: "Privacy 1", title: "Notice of Privacy Practices", description: "Provide individuals with a clear notice describing uses, disclosures, and rights regarding their health information.", domain: "Privacy Rule" },
      { controlId: "Privacy 2", title: "Individual Rights", description: "Honor individual rights to access, amend, and receive an accounting of disclosures of their health information.", domain: "Privacy Rule" },
      { controlId: "Breach Notification", title: "Breach Notification", description: "Notify affected individuals, HHS, and in some cases the media of breaches of unsecured PHI.", domain: "Privacy Rule" },
    ],
  },

  hitrust: {
    version: "CSF v11",
    sourceUrl: "https://hitrustalliance.net/",
    controls: [
      { controlId: "00.a", title: "Information Security Management Program", description: "Develop and maintain an information security management program aligned to organizational objectives and regulatory obligations.", domain: "Information Protection Program" },
      { controlId: "00.b", title: "Risk Management Program", description: "Establish and operate a risk management program that identifies, assesses, and manages information security risk.", domain: "Information Protection Program" },
      { controlId: "01.a", title: "Access Control Policy", description: "Implement an access control policy governing user registration, privilege management, and review of access rights.", domain: "Access Control" },
      { controlId: "01.b", title: "User Registration and Provisioning", description: "Register users, grant access based on least privilege, and maintain formal records of authorized access.", domain: "Access Control" },
      { controlId: "01.c", title: "User Access Reviews", description: "Review user access rights, including privileged accounts, at defined intervals and upon role change.", domain: "Access Control" },
      { controlId: "01.d", title: "Segregation of Duties", description: "Separate conflicting duties and areas of responsibility to reduce the risk of unauthorized or unintentional activity.", domain: "Access Control" },
      { controlId: "01.e", title: "Privileged Access Management", description: "Restrict and monitor the allocation and use of privileged access rights.", domain: "Access Control" },
      { controlId: "01.f", title: "Authentication", description: "Implement authentication mechanisms including password management and, where appropriate, multifactor authentication.", domain: "Access Control" },
      { controlId: "01.g", title: "Remote Access", description: "Authorize, monitor, and control remote access through secure and documented mechanisms.", domain: "Access Control" },
      { controlId: "02.a", title: "User Responsibilities", description: "Document and communicate user responsibilities for the protection of access credentials and information assets.", domain: "Access Control" },
      { controlId: "02.b", title: "Clean Desk and Screen Policy", description: "Protect information on desks and screens from unauthorized access or disclosure.", domain: "Access Control" },
      { controlId: "06.a", title: "End User Computing", description: "Secure end-user computing environments, including mobile devices and teleworking.", domain: "Access Control" },
      { controlId: "07.a", title: "Network Controls", description: "Manage and secure networks to protect information in transit and services from compromise.", domain: "Access Control" },
      { controlId: "07.b", title: "Network Segmentation", description: "Segregate networks and network services to limit the impact of compromise.", domain: "Access Control" },
      { controlId: "08.a", title: "Acceptable Use of Assets", description: "Establish rules governing the acceptable use of information assets and resources.", domain: "Asset Management" },
      { controlId: "08.b", title: "Asset Inventory", description: "Maintain an inventory of information assets, owners, and classifications.", domain: "Asset Management" },
      { controlId: "08.c", title: "Information Classification", description: "Classify information and label assets according to sensitivity and criticality.", domain: "Asset Management" },
      { controlId: "08.d", title: "Media Handling", description: "Implement procedures for the handling, storage, transport, and disposal of removable media.", domain: "Asset Management" },
      { controlId: "08.e", title: "Asset Disposal", description: "Securely dispose of assets and media to prevent unauthorized disclosure of information.", domain: "Asset Management" },
      { controlId: "09.a", title: "Physical Security Perimeter", description: "Establish physical security perimeters to protect areas that contain information processing facilities.", domain: "Physical and Environmental Security" },
      { controlId: "09.b", title: "Physical Access Controls", description: "Control and monitor physical access to facilities and protect entry points.", domain: "Physical and Environmental Security" },
      { controlId: "09.c", title: "Environmental Security", description: "Protect information processing facilities against power failures, fire, and other environmental threats.", domain: "Physical and Environmental Security" },
      { controlId: "10.a", title: "Human Resources Security", description: "Screen personnel, define roles and responsibilities, and manage security obligations during employment and upon termination.", domain: "Human Resources Security" },
      { controlId: "10.b", title: "Security Awareness and Training", description: "Provide ongoing security awareness and skills training relevant to each individual's role.", domain: "Human Resources Security" },
      { controlId: "10.c", title: "Personnel Termination and Transfer", description: "Revoke access and secure information assets upon termination or transfer of personnel.", domain: "Human Resources Security" },
      { controlId: "12.a", title: "Security Incident Management", description: "Establish responsibilities and procedures for detecting, responding to, and reporting security incidents.", domain: "Security Incident Management, E-Discovery, and Cloud" },
      { controlId: "12.b", title: "Incident Response Plan", description: "Develop and maintain an incident response plan and test it at defined intervals.", domain: "Security Incident Management, E-Discovery, and Cloud" },
      { controlId: "12.c", title: "Evidence and Forensics", description: "Protect and preserve evidence related to security incidents for investigation and reporting.", domain: "Security Incident Management, E-Discovery, and Cloud" },
      { controlId: "13.a", title: "Business Continuity and Disaster Recovery", description: "Establish and test business continuity and disaster recovery plans to maintain operations during disruptions.", domain: "Business Continuity Management" },
      { controlId: "13.b", title: "Data Backup and Restoration", description: "Back up information, software, and system images and test restoration at defined intervals.", domain: "Business Continuity Management" },
      { controlId: "15.a", title: "Third-Party Assurance", description: "Assess and monitor the security posture of vendors and business partners, including contractual requirements.", domain: "Third-Party Assurance" },
      { controlId: "15.b", title: "Third-Party Agreements", description: "Define security, privacy, and breach notification requirements in agreements with third parties.", domain: "Third-Party Assurance" },
      { controlId: "15.c", title: "Subcontracting and Supply Chain", description: "Manage and monitor subcontracting and supply chain relationships to ensure controls remain effective.", domain: "Third-Party Assurance" },
      { controlId: "16.a", title: "Software Development Life Cycle", description: "Manage the secure development, testing, and release of software and systems.", domain: "Systems Development and Maintenance" },
      { controlId: "16.b", title: "Change Management", description: "Control and record changes to production systems, including authorization, testing, and approval.", domain: "Systems Development and Maintenance" },
      { controlId: "16.c", title: "Vulnerability Management", description: "Identify, assess, and remediate technical vulnerabilities across information systems.", domain: "Systems Development and Maintenance" },
      { controlId: "16.d", title: "Malicious Software Protection", description: "Deploy and maintain controls to prevent, detect, and respond to malicious software.", domain: "Systems Development and Maintenance" },
      { controlId: "16.e", title: "Cryptographic Controls", description: "Implement cryptographic controls for the protection of information at rest and in transit.", domain: "Systems Development and Maintenance" },
      { controlId: "16.f", title: "Audit Logging and Monitoring", description: "Produce and protect audit logs and monitor systems for unauthorized activity.", domain: "Systems Development and Maintenance" },
      { controlId: "16.g", title: "Security Configuration Management", description: "Establish and maintain secure baseline configurations for systems and network devices.", domain: "Systems Development and Maintenance" },
      { controlId: "17.a", title: "Cloud Computing Security", description: "Manage security responsibilities for cloud services, including data protection, access, and provider oversight.", domain: "Cloud Security" },
      { controlId: "18.a", title: "Data Protection and Privacy", description: "Establish controls to protect personal information in accordance with applicable privacy laws and regulations.", domain: "Data Protection and Privacy" },
      { controlId: "19.a", title: "Policies and Procedures", description: "Establish, document, approve, and communicate security and privacy policies and procedures.", domain: "Information Security Management System" },
      { controlId: "20.a", title: "Internal Audit and Compliance", description: "Conduct internal audits of the security and privacy program and address findings.", domain: "Information Security Management System" },
    ],
  },

  "fda-21-cfr-part-11": {
    version: "21 CFR Part 11",
    sourceUrl: "https://www.ecfr.gov/current/title-21/chapter-I/subchapter-A/part-11",
    controls: [
      { controlId: "11.10(a)", title: "System Validation", description: "Validate computerized systems to ensure accuracy, reliability, consistent intended performance, and the ability to discern invalid or altered records.", domain: "Electronic Records" },
      { controlId: "11.10(b)", title: "Record Reproduction Accuracy", description: "Generate accurate and complete copies of records in both human readable and electronic form for inspection and copying.", domain: "Electronic Records" },
      { controlId: "11.10(c)", title: "Record Protection", description: "Protect records to enable their accurate and ready retrieval throughout the records retention period.", domain: "Electronic Records" },
      { controlId: "11.10(d)", title: "System Access Limitation", description: "Limit system access to authorized individuals.", domain: "Electronic Records" },
      { controlId: "11.10(e)", title: "Audit Trail", description: "Use secure, computer-generated, time-stamped audit trails to independently record the date and time of operator entries and actions that create, modify, or delete electronic records.", domain: "Electronic Records" },
      { controlId: "11.10(f)", title: "Operational System Checks", description: "Use operational system checks to enforce the sequencing of steps and events as appropriate.", domain: "Electronic Records" },
      { controlId: "11.10(g)", title: "Authority Checks", description: "Use authority checks to ensure only authorized individuals can use the system, electronically sign a record, access the operation, or perform the function.", domain: "Electronic Records" },
      { controlId: "11.10(h)", title: "Device Checks", description: "Use device checks to determine the validity of the source of data input or operational instruction.", domain: "Electronic Records" },
      { controlId: "11.10(i)", title: "Personnel Qualification", description: "Determine that persons who develop, maintain, or use electronic record systems have the education, training, and experience to perform their assigned functions.", domain: "Electronic Records" },
      { controlId: "11.10(j)", title: "Controlled Documentation", description: "Establish and adhere to written policies holding individuals accountable for actions initiated under their electronic signatures.", domain: "Electronic Records" },
      { controlId: "11.10(k)", title: "Signature Records Controls", description: "Use appropriate controls for systems without device checks to ensure that signatories cannot easily repudiate signed records as not genuine.", domain: "Electronic Records" },
      { controlId: "11.30", title: "Open Systems Controls", description: "Apply additional measures such as document encryption and digital signatures for records in open systems.", domain: "Electronic Records" },
      { controlId: "11.50(a)", title: "Signed Record Display", description: "Electronic signatures and handwritten signatures executed to electronic records must be linked to their respective electronic records to ensure they cannot be excised or altered.", domain: "Electronic Signatures" },
      { controlId: "11.50(b)", title: "Signature Components Display", description: "Electronic signature components display at least the printed name, date and time, and the meaning of the signature.", domain: "Electronic Signatures" },
      { controlId: "11.70", title: "Signature/E-Record Linking", description: "Ensure electronic signatures are linked to their respective electronic records, including that the signature cannot be transferred or reused for another record.", domain: "Electronic Signatures" },
      { controlId: "11.100(a)", title: "Unique Electronic Signature", description: "Ensure each electronic signature is unique to one individual and is not reused by or reassigned to anyone else.", domain: "Electronic Signatures" },
      { controlId: "11.100(b)", title: "Signature Identity Verification", description: "Verify the identity of individuals prior to establishing or assigning electronic signatures.", domain: "Electronic Signatures" },
      { controlId: "11.100(c)", title: "Signature Certification", description: "Ensure persons using electronic signatures certify in writing that the signatures in their system are legally binding.", domain: "Electronic Signatures" },
      { controlId: "11.200(a)", title: "Signature/Manifestation of Signing", description: "Ensure electronic signatures consist of at least two distinct identification components such as an identification code and password.", domain: "Electronic Signatures" },
      { controlId: "11.200(b)", title: "Signature Integrity", description: "Ensure electronic signatures based on biometrics are designed to ensure that they cannot be used by anyone other than their genuine owners.", domain: "Electronic Signatures" },
      { controlId: "11.300(a)", title: "Identification Code/Password Controls", description: "Maintain the uniqueness of each combined identification code and password and ensure they are not reused.", domain: "Electronic Signatures" },
      { controlId: "11.300(b)", title: "Password Management", description: "Ensure identification codes and passwords are periodically checked, recalled, or revised and that lost or compromised codes are deactivated.", domain: "Electronic Signatures" },
      { controlId: "11.300(c)", title: "Security of Codes and Passwords", description: "Use strict, documented measures to detect unauthorized attempts to use identification codes and passwords.", domain: "Electronic Signatures" },
      { controlId: "11.300(d)", title: "Initial and Periodic Testing", description: "Perform initial and periodic testing of devices to ensure the proper functioning of identification codes and passwords.", domain: "Electronic Signatures" },
    ],
  },
};
