import type { Catalog } from "./index";

export const industryCatalogs: Record<string, Catalog> = {
  nis2: {
    version: "Directive (EU) 2022/2555",
    sourceUrl: "https://digital-strategy.ec.europa.eu/en/policies/nis2-directive",
    controls: [
      { controlId: "Art. 21(2)(a)", title: "Risk Analysis and Information Security Policies", description: "Implement policies on risk analysis and information system security to cover the entire organization.", domain: "Cybersecurity Risk Management" },
      { controlId: "Art. 21(2)(b)", title: "Incident Handling", description: "Establish procedures for handling, reporting, and recovering from incidents.", domain: "Cybersecurity Risk Management" },
      { controlId: "Art. 21(2)(c)", title: "Business Continuity", description: "Maintain business continuity management, backup management, and disaster recovery with crisis management capabilities.", domain: "Cybersecurity Risk Management" },
      { controlId: "Art. 21(2)(d)", title: "Supply Chain Security", description: "Secure the supply chain, including security aspects of relationships with suppliers and service providers.", domain: "Cybersecurity Risk Management" },
      { controlId: "Art. 21(2)(e)", title: "Security in Acquisition and Development", description: "Embed security measures in the acquisition, development, and maintenance of network and information systems.", domain: "Cybersecurity Risk Management" },
      { controlId: "Art. 21(2)(f)", title: "Vulnerability Assessment", description: "Assess the effectiveness of cybersecurity risk-management measures, including vulnerability handling and disclosure.", domain: "Cybersecurity Risk Management" },
      { controlId: "Art. 21(2)(g)", title: "Basic Cyber Hygiene and Training", description: "Implement basic cyber hygiene practices and cybersecurity training, including awareness of phishing and social engineering.", domain: "Cybersecurity Risk Management" },
      { controlId: "Art. 21(2)(h)", title: "Cryptography and Encryption", description: "Use cryptography and, where appropriate, encryption to protect data at rest and in transit.", domain: "Cybersecurity Risk Management" },
      { controlId: "Art. 21(2)(i)", title: "Human Resources Security", description: "Apply human resources security measures covering hiring, roles, and the lifecycle of staff access.", domain: "Cybersecurity Risk Management" },
      { controlId: "Art. 21(2)(j)", title: "Access Control and Identity Management", description: "Implement access control policies, asset management, and identity management procedures.", domain: "Cybersecurity Risk Management" },
      { controlId: "Art. 21(2)(k)", title: "MFA and Continuous Authentication", description: "Use multi-factor authentication or continuous authentication solutions and secure voice, video, and text communications.", domain: "Cybersecurity Risk Management" },
      { controlId: "Art. 20", title: "Governance of Cybersecurity", description: "Ensure management bodies approve cybersecurity risk-management measures, oversee their implementation, and receive training.", domain: "Governance and Reporting" },
      { controlId: "Art. 20(2)", title: "Management Accountability", description: "Hold members of management bodies liable for failure to adopt and supervise cybersecurity measures, subject to national rules.", domain: "Governance and Reporting" },
      { controlId: "Art. 23", title: "Early Warning", description: "Notify competent authorities without undue delay (within 24 hours) of significant incidents, including an early warning.", domain: "Incident Reporting" },
      { controlId: "Art. 23(3)", title: "Incident Notification", description: "Submit an incident notification within 72 hours and a final report within one month of the significant incident.", domain: "Incident Reporting" },
      { controlId: "Art. 23(5)", title: "User Information", description: "Inform users potentially affected by a significant cyber threat or incident of protective or remedial measures.", domain: "Incident Reporting" },
      { controlId: "Art. 24", title: "Enforcement and Registration", description: "Register as essential or important entities and comply with supervisory and enforcement measures of competent authorities.", domain: "Supervision and Enforcement" },
      { controlId: "Art. 27", title: "European Cyber Crises Framework", description: "Cooperate within the cyber crisis management framework for coordinated responses to large-scale incidents.", domain: "Cooperation and Coordination" },
      { controlId: "Art. 9", title: "Accountability and Compliance", description: "Adopt technical, organizational, and security measures to manage cybersecurity risk and demonstrate compliance with the directive.", domain: "General Requirements" },
    ],
  },

  tisax: {
    version: "ISA 6.0",
    sourceUrl: "https://portal.enx.com/en-US/TISAX/",
    controls: [
      { controlId: "P1.1", title: "Information Security Policy", description: "Define and communicate a security policy that reflects the organization's approach to protecting information assets.", domain: "Information Security Policy" },
      { controlId: "P2.1", title: "Information Security Roles and Responsibilities", description: "Assign clear roles and responsibilities for information security across the organization.", domain: "Information Security Organization" },
      { controlId: "P3.1", title: "Security Awareness and Training", description: "Provide security awareness and training to personnel commensurate with their roles.", domain: "Personnel" },
      { controlId: "P4.1", title: "Risk Management", description: "Establish a risk management process that identifies, assesses, and treats information security risks.", domain: "Information Risk Management" },
      { controlId: "P5.1", title: "Incident Management", description: "Detect, respond to, and document security incidents, including reporting to authorities and customers.", domain: "Security Incident Management" },
      { controlId: "P6.1", title: "Business Continuity Management", description: "Establish a business continuity management process to maintain operations during disruptions.", domain: "Business Continuity Management" },
      { controlId: "P7.1", title: "Third-Party and Customer Data Protection", description: "Protect the confidentiality, integrity, and availability of customer and third-party data.", domain: "Business Partner and Customer Requirements" },
      { controlId: "P8.1", title: "Information Classification", description: "Classify information and data according to confidentiality and define handling requirements.", domain: "Classification and Handling of Information" },
      { controlId: "P9.1", title: "Data Protection and Privacy", description: "Comply with applicable data protection laws for the processing of personal data.", domain: "Data Protection and Privacy" },
      { controlId: "V1.1", title: "Asset Management", description: "Maintain an inventory of information assets and assign ownership and classification.", domain: "Asset Management" },
      { controlId: "V2.1", title: "Physical Security", description: "Protect facilities, equipment, and media against unauthorized physical access and environmental threats.", domain: "Physical Security" },
      { controlId: "V3.1", title: "Access Control", description: "Implement access control mechanisms covering user registration, authentication, and authorization.", domain: "Access Control" },
      { controlId: "V4.1", title: "Network and Communication Security", description: "Secure networks, including segmentation, firewalling, and protection of information in transit.", domain: "Communication and Network Security" },
      { controlId: "V5.1", title: "Cryptography", description: "Use cryptographic controls to protect the confidentiality, integrity, and authenticity of information.", domain: "Communication and Network Security" },
      { controlId: "V6.1", title: "System Development and Maintenance", description: "Manage secure development, change management, and the operation of systems in production.", domain: "Development and Maintenance" },
      { controlId: "V7.1", title: "IT Operations", description: "Operate systems in accordance with documented procedures, including monitoring, backup, and capacity management.", domain: "Development and Maintenance" },
      { controlId: "V8.1", title: "Vulnerability Management", description: "Identify and remediate technical vulnerabilities across systems and applications.", domain: "Development and Maintenance" },
      { controlId: "V9.1", title: "Malware Protection", description: "Protect systems against malware through preventive controls and response measures.", domain: "Development and Maintenance" },
      { controlId: "V10.1", title: "Logging and Monitoring", description: "Collect, protect, and review audit logs to detect and investigate security events.", domain: "Development and Maintenance" },
      { controlId: "V11.1", title: "Cryptographic Key Management", description: "Manage the lifecycle of cryptographic keys used to protect information.", domain: "Development and Maintenance" },
    ],
  },

  cobit: {
    version: "2019",
    sourceUrl: "https://www.isaca.org/resources/cobit",
    controls: [
      { controlId: "APO01", title: "Manage the I&T Management Framework", description: "Clarify and maintain the governance and management approach to align with enterprise goals.", domain: "Align, Plan, and Organize (APO)" },
      { controlId: "APO02", title: "Manage Strategy", description: "Translate enterprise goals into an actionable I&T strategy and road map.", domain: "Align, Plan, and Organize (APO)" },
      { controlId: "APO03", title: "Manage Enterprise Architecture", description: "Establish an enterprise architecture that enables business objectives through I&T.", domain: "Align, Plan, and Organize (APO)" },
      { controlId: "APO04", title: "Manage Innovation", description: "Identify and exploit emerging technologies and services to drive business value.", domain: "Align, Plan, and Organize (APO)" },
      { controlId: "APO06", title: "Manage Budget and Costs", description: "Manage the budget for I&T solutions and services in alignment with strategy.", domain: "Align, Plan, and Organize (APO)" },
      { controlId: "APO07", title: "Manage Workforce", description: "Manage human resources to ensure competent personnel support enterprise objectives.", domain: "Align, Plan, and Organize (APO)" },
      { controlId: "APO08", title: "Manage Relationships", description: "Manage relationships between business and I&T to ensure objectives are reached.", domain: "Align, Plan, and Organize (APO)" },
      { controlId: "APO09", title: "Manage Service Agreements", description: "Align I&T services with enterprise requirements through service agreements.", domain: "Align, Plan, and Organize (APO)" },
      { controlId: "APO11", title: "Manage Quality", description: "Establish a quality management system to ensure I&T solutions meet requirements.", domain: "Align, Plan, and Organize (APO)" },
      { controlId: "APO12", title: "Manage Risk", description: "Integrate the management of I&T-related risk into the enterprise risk management approach.", domain: "Align, Plan, and Organize (APO)" },
      { controlId: "APO13", title: "Manage Security", description: "Define, operate, and monitor a system for the management of information security.", domain: "Align, Plan, and Organize (APO)" },
      { controlId: "APO14", title: "Manage Data", description: "Manage data assets to ensure quality, consistency, and controlled access.", domain: "Align, Plan, and Organize (APO)" },
      { controlId: "BAI01", title: "Manage Programs and Projects", description: "Initiate, plan, and execute programs and projects to deliver value on time and in budget.", domain: "Build, Acquire, and Implement (BAI)" },
      { controlId: "BAI02", title: "Manage Requirements Definition", description: "Define and maintain solution requirements to enable effective acquisition or development.", domain: "Build, Acquire, and Implement (BAI)" },
      { controlId: "BAI03", title: "Manage Solutions Identification and Build", description: "Identify, design, and build solutions in line with enterprise requirements.", domain: "Build, Acquire, and Implement (BAI)" },
      { controlId: "BAI04", title: "Manage Availability and Capacity", description: "Balance current and future needs for capacity and availability.", domain: "Build, Acquire, and Implement (BAI)" },
      { controlId: "BAI05", title: "Manage Organizational Change Enablement", description: "Maximize the likelihood of successful adoption of organizational change.", domain: "Build, Acquire, and Implement (BAI)" },
      { controlId: "BAI06", title: "Manage IT Changes", description: "Manage changes to I&T in a controlled manner, including authorization, testing, and release.", domain: "Build, Acquire, and Implement (BAI)" },
      { controlId: "BAI07", title: "Manage Change Acceptance and Transitioning", description: "Formally accept and transition new or changed solutions into operations.", domain: "Build, Acquire, and Implement (BAI)" },
      { controlId: "BAI08", title: "Manage Knowledge", description: "Maintain and manage knowledge assets to support decision making and operations.", domain: "Build, Acquire, and Implement (BAI)" },
      { controlId: "BAI10", title: "Manage Configuration", description: "Define and maintain configurations and maintain awareness of configuration items.", domain: "Build, Acquire, and Implement (BAI)" },
      { controlId: "BAI11", title: "Manage Projects", description: "Manage projects in alignment with the program and portfolio management approach.", domain: "Build, Acquire, and Implement (BAI)" },
      { controlId: "DSS01", title: "Manage Operations", description: "Coordinate and execute operational activities required to deliver I&T services.", domain: "Deliver, Service, and Support (DSS)" },
      { controlId: "DSS02", title: "Manage Service Requests and Incidents", description: "Restore normal service in a timely manner and record, respond, and resolve incidents.", domain: "Deliver, Service, and Support (DSS)" },
      { controlId: "DSS03", title: "Manage Problems", description: "Identify and resolve root causes of incidents and prevent recurrence.", domain: "Deliver, Service, and Support (DSS)" },
      { controlId: "DSS04", title: "Manage Continuity", description: "Establish and maintain business continuity and IT disaster recovery plans.", domain: "Deliver, Service, and Support (DSS)" },
      { controlId: "DSS05", title: "Manage Security Services", description: "Protect enterprise information to maintain acceptable levels of security risk.", domain: "Deliver, Service, and Support (DSS)" },
      { controlId: "DSS06", title: "Manage Business Process Controls", description: "Define and maintain business process controls to ensure information integrity.", domain: "Deliver, Service, and Support (DSS)" },
      { controlId: "MEA01", title: "Monitor, Evaluate, and Assess Performance and Conformance", description: "Monitor performance and conformance against objectives, targets, and requirements.", domain: "Monitor, Evaluate, and Assess (MEA)" },
      { controlId: "MEA02", title: "Monitor, Evaluate, and Assess the System of Internal Control", description: "Continuously monitor and assess the effectiveness of internal control.", domain: "Monitor, Evaluate, and Assess (MEA)" },
      { controlId: "MEA03", title: "Monitor, Evaluate, and Assess Compliance With External Requirements", description: "Monitor and assess compliance with external laws, regulations, and contractual obligations.", domain: "Monitor, Evaluate, and Assess (MEA)" },
      { controlId: "EDM01", title: "Ensure Governance Framework Setting and Maintenance", description: "Establish and maintain a governance framework aligned to stakeholder value.", domain: "Evaluate, Direct, and Monitor (EDM)" },
      { controlId: "EDM02", title: "Ensure Benefits Delivery", description: "Optimize the value contribution from I&T-enabled investments and services.", domain: "Evaluate, Direct, and Monitor (EDM)" },
      { controlId: "EDM03", title: "Ensure Risk Optimization", description: "Ensure that I&T-related risk is addressed within acceptable levels.", domain: "Evaluate, Direct, and Monitor (EDM)" },
      { controlId: "EDM04", title: "Ensure Resource Optimization", description: "Ensure that capabilities and resources are available to support enterprise objectives.", domain: "Evaluate, Direct, and Monitor (EDM)" },
      { controlId: "EDM05", title: "Ensure Stakeholder Engagement", description: "Ensure effective engagement of stakeholders in governance decisions.", domain: "Evaluate, Direct, and Monitor (EDM)" },
    ],
  },

  fedramp: {
    version: "Rev 5",
    sourceUrl: "https://www.fedramp.gov/",
    controls: [
      { controlId: "AC-2", title: "Account Management", description: "Manage information system accounts, including identification, authorization, and lifecycle.", domain: "Access Control" },
      { controlId: "AC-3", title: "Access Enforcement", description: "Enforce approved authorizations for logical access to information and system resources.", domain: "Access Control" },
      { controlId: "AC-6", title: "Least Privilege", description: "Employ least privilege, allowing only authorized access for users required for job functions.", domain: "Access Control" },
      { controlId: "AC-7", title: "Unsuccessful Logon Attempts", description: "Enforce a limit of consecutive invalid logon attempts and lock the account.", domain: "Access Control" },
      { controlId: "AC-17", title: "Remote Access", description: "Authorize, monitor, and control remote access to the system.", domain: "Access Control" },
      { controlId: "AC-20", title: "Use of External Systems", description: "Establish terms and conditions for the use of external information systems.", domain: "Access Control" },
      { controlId: "AT-2", title: "Literacy Training and Awareness", description: "Provide security and privacy literacy training that is role-based and occurs at defined intervals.", domain: "Awareness and Training" },
      { controlId: "AU-2", title: "Event Logging", description: "Identify the system events that are logged and the events that require logging.", domain: "Audit and Accountability" },
      { controlId: "AU-6", title: "Audit Record Review, Analysis, and Reporting", description: "Review and analyze audit records for indications of inappropriate or unusual activity.", domain: "Audit and Accountability" },
      { controlId: "CA-2", title: "Control Assessments", description: "Assess the effectiveness of controls in achieving stated objectives at defined intervals.", domain: "Assessment, Authorization, and Monitoring" },
      { controlId: "CA-7", title: "Continuous Monitoring", description: "Develop and implement a continuous monitoring strategy for the system and its controls.", domain: "Assessment, Authorization, and Monitoring" },
      { controlId: "CA-9", title: "Internal System Connections", description: "Authorize internal connections of system components or discrete systems before connection.", domain: "Assessment, Authorization, and Monitoring" },
      { controlId: "CM-2", title: "Baseline Configuration", description: "Develop and maintain a baseline configuration of the system and components.", domain: "Configuration Management" },
      { controlId: "CM-6", title: "Configuration Settings", description: "Establish and enforce security configuration settings for products employed.", domain: "Configuration Management" },
      { controlId: "CM-7", title: "Least Functionality", description: "Restrict functionality to the minimum required for system operation.", domain: "Configuration Management" },
      { controlId: "CM-8", title: "System Component Inventory", description: "Develop, document, and maintain an inventory of system components.", domain: "Configuration Management" },
      { controlId: "CP-2", title: "Contingency Plan", description: "Develop and maintain a contingency plan for the system to enable recovery after disruption.", domain: "Contingency Planning" },
      { controlId: "CP-9", title: "System Backup", description: "Conduct backups of user-level and system-level information at defined frequencies.", domain: "Contingency Planning" },
      { controlId: "IA-2", title: "Identification and Authentication for Organizational Users", description: "Uniquely identify and authenticate organizational users and processes.", domain: "Identification and Authentication" },
      { controlId: "IA-5", title: "Authenticator Management", description: "Manage system authenticators, including initial distribution and reset.", domain: "Identification and Authentication" },
      { controlId: "IR-4", title: "Incident Handling", description: "Implement incident handling capability for preparation, detection, analysis, containment, and recovery.", domain: "Incident Response" },
      { controlId: "IR-6", title: "Incident Reporting", description: "Require personnel to report suspected incidents, and report incidents to authorities within defined time periods.", domain: "Incident Response" },
      { controlId: "PL-2", title: "System Security and Privacy Plans", description: "Develop and maintain a system security and privacy plan describing the system and its controls.", domain: "Planning" },
      { controlId: "RA-3", title: "Risk Assessment", description: "Conduct risk assessments to identify and analyze risk to operations and assets.", domain: "Risk Assessment" },
      { controlId: "RA-5", title: "Vulnerability Monitoring and Scanning", description: "Scan for vulnerabilities and remediate deficiencies on a defined schedule.", domain: "Risk Assessment" },
      { controlId: "SA-9", title: "External System Services", description: "Employ external system services consistent with organizational security requirements.", domain: "System and Services Acquisition" },
      { controlId: "SC-7", title: "Boundary Protection", description: "Monitor and control communications at the external boundary and key internal boundaries.", domain: "System and Communications Protection" },
      { controlId: "SC-8", title: "Transmission Confidentiality and Integrity", description: "Protect the confidentiality and integrity of transmitted information.", domain: "System and Communications Protection" },
      { controlId: "SC-12", title: "Cryptographic Key Establishment and Management", description: "Establish and manage cryptographic keys for required cryptography.", domain: "System and Communications Protection" },
      { controlId: "SC-13", title: "Cryptographic Protection", description: "Implement cryptographic mechanisms in accordance with applicable standards.", domain: "System and Communications Protection" },
      { controlId: "SC-28", title: "Protection of Information at Rest", description: "Protect the confidentiality and integrity of information at rest.", domain: "System and Communications Protection" },
      { controlId: "SI-2", title: "Flaw Remediation", description: "Identify, report, and correct system flaws in a timely manner.", domain: "System and Information Integrity" },
      { controlId: "SI-3", title: "Malicious Code Protection", description: "Employ malicious code protection mechanisms at key locations and update signatures.", domain: "System and Information Integrity" },
      { controlId: "SI-4", title: "System Monitoring", description: "Monitor the system to detect attacks and unauthorized activity.", domain: "System and Information Integrity" },
      { controlId: "SI-5", title: "Security Alerts, Advisories, and Directives", description: "Receive and generate system security alerts, advisories, and directives.", domain: "System and Information Integrity" },
      { controlId: "SI-12", title: "Information Handling and Retention", description: "Handle and retain information within the system in accordance with applicable policy.", domain: "System and Information Integrity" },
      { controlId: "FedRAMP SP", title: "Security Assessment Plan", description: "Develop a security assessment plan documenting the scope, approach, and methodology of the security assessment.", domain: "Assessment and Authorization" },
      { controlId: "FedRAMP SAR", title: "Security Assessment Report", description: "Produce a security assessment report with findings, risk ratings, and recommendations for remediation.", domain: "Assessment and Authorization" },
      { controlId: "FedRAMP POA&M", title: "Plan of Action and Milestones", description: "Track and remediate security weaknesses through a plan of action and milestones reviewed at defined intervals.", domain: "Assessment and Authorization" },
      { controlId: "FedRAMP 3PAO", title: "Independent Assessment", description: "Engage an accredited third-party assessment organization (3PAO) to perform the security assessment.", domain: "Assessment and Authorization" },
    ],
  },
};
