import type { Catalog } from "./index";

export const isoCatalogs: Record<string, Catalog> = {
  "iso-27001": {
    version: "2022",
    sourceUrl: "https://www.iso.org/standard/27001",
    controls: [
      { controlId: "A.5.1", title: "Policies for Information Security", description: "Information security policy and topic-specific policies are defined, approved, published, communicated, acknowledged, and reviewed.", domain: "Organizational Controls" },
      { controlId: "A.5.2", title: "Information Security Roles and Responsibilities", description: "Information security roles and responsibilities are defined and assigned.", domain: "Organizational Controls" },
      { controlId: "A.5.3", title: "Segregation of Duties", description: "Conflicting duties and areas of responsibility are segregated to reduce conflict of interest and risk.", domain: "Organizational Controls" },
      { controlId: "A.5.4", title: "Management Responsibilities", description: "Management requires personnel to apply information security in accordance with policy.", domain: "Organizational Controls" },
      { controlId: "A.5.5", title: "Contact with Authorities", description: "The organization establishes contact with relevant authorities on information security matters.", domain: "Organizational Controls" },
      { controlId: "A.5.6", title: "Contact with Special Interest Groups", description: "The organization establishes contact with special interest groups and professional associations.", domain: "Organizational Controls" },
      { controlId: "A.5.7", title: "Threat Intelligence", description: "Information relating to information security threats is collected and analyzed to produce threat intelligence.", domain: "Organizational Controls" },
      { controlId: "A.5.8", title: "Information Security in Project Management", description: "Information security is integrated into project management across the project life cycle.", domain: "Organizational Controls" },
      { controlId: "A.5.9", title: "Inventory of Information and Other Associated Assets", description: "An inventory of information and other associated assets is developed and maintained.", domain: "Organizational Controls" },
      { controlId: "A.5.10", title: "Acceptable Use of Information and Other Associated Assets", description: "Rules for the acceptable use of information and other assets are identified, documented, and implemented.", domain: "Organizational Controls" },
      { controlId: "A.5.11", title: "Return of Assets", description: "Personnel return all organizational assets in their possession upon termination or change.", domain: "Organizational Controls" },
      { controlId: "A.5.12", title: "Classification of Information", description: "Information is classified according to legal, contractual, and business requirements.", domain: "Organizational Controls" },
      { controlId: "A.5.13", title: "Labelling of Information", description: "Procedures for labelling information are developed and implemented in line with the classification scheme.", domain: "Organizational Controls" },
      { controlId: "A.5.14", title: "Information Transfer", description: "Rules and controls for transferring information are defined, implemented, and maintained.", domain: "Organizational Controls" },
      { controlId: "A.5.15", title: "Access Control", description: "Rules to control physical and logical access are established and implemented based on security requirements.", domain: "Organizational Controls" },
      { controlId: "A.5.16", title: "Identity Management", description: "The full life cycle of identities is managed in line with business needs.", domain: "Organizational Controls" },
      { controlId: "A.5.17", title: "Authentication Information", description: "The allocation and management of authentication information is governed by defined processes.", domain: "Organizational Controls" },
      { controlId: "A.5.18", title: "Access Rights", description: "Access rights are provisioned, reviewed, and revoked in line with the access control policy.", domain: "Organizational Controls" },
      { controlId: "A.5.19", title: "Information Security in Supplier Relationships", description: "Processes and procedures to manage information security risks from suppliers are established and implemented.", domain: "Organizational Controls" },
      { controlId: "A.5.20", title: "Addressing Information Security within Supplier Agreements", description: "Relevant information security requirements are established and agreed with each supplier.", domain: "Organizational Controls" },
      { controlId: "A.5.21", title: "Managing Information Security in the ICT Supply Chain", description: "Processes to manage risks associated with the ICT products and services supply chain are established.", domain: "Organizational Controls" },
      { controlId: "A.5.22", title: "Monitoring, Review and Change Management of Supplier Services", description: "Supplier services are monitored, reviewed, and audited, and changes are managed.", domain: "Organizational Controls" },
      { controlId: "A.5.23", title: "Information Security for Use of Cloud Services", description: "Processes for acquisition, use, management, and exit from cloud services are established.", domain: "Organizational Controls" },
      { controlId: "A.5.24", title: "Information Security Incident Management Planning and Preparation", description: "The organization plans and prepares to manage information security incidents.", domain: "Organizational Controls" },
      { controlId: "A.5.25", title: "Assessment and Decision on Information Security Events", description: "Information security events are assessed and decisions made on whether to classify them as incidents.", domain: "Organizational Controls" },
      { controlId: "A.5.26", title: "Response to Information Security Incidents", description: "Information security incidents are responded to in accordance with documented procedures.", domain: "Organizational Controls" },
      { controlId: "A.5.27", title: "Learning from Information Security Incidents", description: "Knowledge gained from information security incidents is used to improve the security posture.", domain: "Organizational Controls" },
      { controlId: "A.5.28", title: "Collection of Evidence", description: "Evidence related to information security events is collected, preserved, and presented consistent with legal requirements.", domain: "Organizational Controls" },
      { controlId: "A.5.29", title: "Information Security during Disruption", description: "The organization plans how to maintain information security during an adverse situation or disruption.", domain: "Organizational Controls" },
      { controlId: "A.5.30", title: "ICT Readiness for Business Continuity", description: "ICT readiness is planned, implemented, maintained, and tested based on continuity objectives.", domain: "Organizational Controls" },
      { controlId: "A.5.31", title: "Legal, Statutory, Regulatory and Contractual Requirements", description: "Legal, statutory, regulatory, and contractual requirements are determined, documented, and kept up to date.", domain: "Organizational Controls" },
      { controlId: "A.5.32", title: "Intellectual Property Rights", description: "The organization protects intellectual property rights using appropriate procedures.", domain: "Organizational Controls" },
      { controlId: "A.5.33", title: "Protection of Records", description: "Records are protected from loss, destruction, falsification, and unauthorized access.", domain: "Organizational Controls" },
      { controlId: "A.5.34", title: "Privacy and Protection of PII", description: "Privacy and protection of personally identifiable information is managed per relevant requirements.", domain: "Organizational Controls" },
      { controlId: "A.5.35", title: "Independent Review of Information Security", description: "The approach to managing information security is reviewed independently at planned intervals.", domain: "Organizational Controls" },
      { controlId: "A.5.36", title: "Compliance with Policies, Rules and Standards for Information Security", description: "Compliance with policies, rules, and standards is reviewed at planned intervals.", domain: "Organizational Controls" },
      { controlId: "A.5.37", title: "Documented Operating Procedures", description: "Operating procedures for information processing facilities are documented and made available.", domain: "Organizational Controls" },
      { controlId: "A.6.1", title: "Screening", description: "Background verification checks are carried out prior to employment, consistent with requirements.", domain: "People Controls" },
      { controlId: "A.6.2", title: "Terms and Conditions of Employment", description: "Employment contracts state responsibilities for information security and include roles, duties, and disciplinary measures.", domain: "People Controls" },
      { controlId: "A.6.3", title: "Information Security Awareness, Education and Training", description: "Personnel receive appropriate awareness, education, and training on information security.", domain: "People Controls" },
      { controlId: "A.6.4", title: "Disciplinary Process", description: "A formal disciplinary process is in place for personnel who commit information security breaches.", domain: "People Controls" },
      { controlId: "A.6.5", title: "Responsibilities after Termination or Change of Employment", description: "Information security responsibilities and duties remain in force after termination or change of employment.", domain: "People Controls" },
      { controlId: "A.6.6", title: "Confidentiality or Non-Disclosure Agreements", description: "Confidentiality or non-disclosure agreements are used where required and reviewed regularly.", domain: "People Controls" },
      { controlId: "A.6.7", title: "Remote Working", description: "Security measures protect information accessed, processed, or stored at remote working locations.", domain: "People Controls" },
      { controlId: "A.6.8", title: "Information Security Event Reporting", description: "Personnel report observed or suspected information security events through appropriate channels promptly.", domain: "People Controls" },
      { controlId: "A.7.1", title: "Physical Security Perimeters", description: "Security perimeters are defined and used to protect areas containing information processing facilities.", domain: "Physical Controls" },
      { controlId: "A.7.2", title: "Physical Entry", description: "Secure areas are protected by appropriate entry controls and access rights.", domain: "Physical Controls" },
      { controlId: "A.7.3", title: "Securing Offices, Rooms and Facilities", description: "Physical security is designed and applied to offices, rooms, and facilities.", domain: "Physical Controls" },
      { controlId: "A.7.4", title: "Physical Security Monitoring", description: "Premises are continuously monitored and unauthorized access is detected and reported.", domain: "Physical Controls" },
      { controlId: "A.7.5", title: "Protecting against Physical and Environmental Threats", description: "Protection is provided against natural disasters and other physical and environmental threats.", domain: "Physical Controls" },
      { controlId: "A.7.6", title: "Working in Secure Areas", description: "Working procedures in secure areas are designed and applied, including control of access and activities.", domain: "Physical Controls" },
      { controlId: "A.7.7", title: "Clear Desk and Clear Screen", description: "Clear desk and clear screen rules are defined and applied to protect information and reduce risks.", domain: "Physical Controls" },
      { controlId: "A.7.8", title: "Equipment Siting and Protection", description: "Equipment is sited and protected to reduce risks from threats and hazards and unauthorized access.", domain: "Physical Controls" },
      { controlId: "A.7.9", title: "Security of Assets Off-Premises", description: "Assets off-premises are protected, taking into account risks of working outside the organization's premises.", domain: "Physical Controls" },
      { controlId: "A.7.10", title: "Storage Media", description: "Storage media are managed through a secure lifecycle from acquisition to disposal.", domain: "Physical Controls" },
      { controlId: "A.7.11", title: "Supporting Utilities", description: "Supporting utilities are protected from failure, including electricity, water, and communications.", domain: "Physical Controls" },
      { controlId: "A.7.12", title: "Cabling Security", description: "Cabling carrying data or supporting services is protected from interception, interference, and damage.", domain: "Physical Controls" },
      { controlId: "A.7.13", title: "Equipment Maintenance", description: "Equipment is correctly maintained to ensure availability and integrity.", domain: "Physical Controls" },
      { controlId: "A.7.14", title: "Secure Disposal or Re-use of Equipment", description: "Equipment is verified to have sensitive data removed prior to disposal or re-use.", domain: "Physical Controls" },
      { controlId: "A.8.1", title: "User Endpoint Devices", description: "Information stored on and processed by user endpoint devices is protected.", domain: "Technological Controls" },
      { controlId: "A.8.2", title: "Privileged Access Rights", description: "The allocation and use of privileged access rights is restricted and managed.", domain: "Technological Controls" },
      { controlId: "A.8.3", title: "Information Access Restriction", description: "Access to information and other associated assets is restricted per established rules.", domain: "Technological Controls" },
      { controlId: "A.8.4", title: "Access to Source Code", description: "Read and write access to source code and development tools is managed appropriately.", domain: "Technological Controls" },
      { controlId: "A.8.5", title: "Secure Authentication", description: "Secure authentication technologies and procedures are implemented based on information access restrictions.", domain: "Technological Controls" },
      { controlId: "A.8.6", title: "Capacity Management", description: "The use of resources is monitored and adjusted to meet capacity requirements.", domain: "Technological Controls" },
      { controlId: "A.8.7", title: "Protection against Malware", description: "Protection against malware is implemented and supported by appropriate user awareness.", domain: "Technological Controls" },
      { controlId: "A.8.8", title: "Management of Technical Vulnerabilities", description: "Information about technical vulnerabilities is obtained, evaluated, and acted upon.", domain: "Technological Controls" },
      { controlId: "A.8.9", title: "Configuration Management", description: "Configurations, including security configurations, are established, documented, implemented, monitored, and reviewed.", domain: "Technological Controls" },
      { controlId: "A.8.10", title: "Information Deletion", description: "Information is deleted when no longer required, in line with retention requirements.", domain: "Technological Controls" },
      { controlId: "A.8.11", title: "Data Masking", description: "Data masking is used in line with policy and business requirements.", domain: "Technological Controls" },
      { controlId: "A.8.12", title: "Data Leakage Prevention", description: "Data leakage prevention measures are applied to detect and prevent unauthorized disclosure.", domain: "Technological Controls" },
      { controlId: "A.8.13", title: "Information Backup", description: "Backup copies of information, software, and systems are maintained and tested at planned intervals.", domain: "Technological Controls" },
      { controlId: "A.8.14", title: "Redundancy of Information Processing Facilities", description: "Information processing facilities are implemented with redundancy sufficient to meet availability requirements.", domain: "Technological Controls" },
      { controlId: "A.8.15", title: "Logging", description: "Logs recording activities, exceptions, faults, and other events are produced, stored, protected, and analyzed.", domain: "Technological Controls" },
      { controlId: "A.8.16", title: "Monitoring Activities", description: "Networks, systems, and applications are monitored for anomalous behavior and incidents are escalated.", domain: "Technological Controls" },
      { controlId: "A.8.17", title: "Clock Synchronization", description: "Clocks of information processing systems are synchronized to a referenced time source.", domain: "Technological Controls" },
      { controlId: "A.8.18", title: "Use of Privileged Utility Programs", description: "Use of utility programs that could override system and application controls is restricted.", domain: "Technological Controls" },
      { controlId: "A.8.19", title: "Installation of Software on Operational Systems", description: "Procedures to manage the installation of software on operational systems are implemented.", domain: "Technological Controls" },
      { controlId: "A.8.20", title: "Networks Security", description: "Networks and network devices are secured, managed, and controlled to protect information.", domain: "Technological Controls" },
      { controlId: "A.8.21", title: "Security of Network Services", description: "Security mechanisms, service levels, and management requirements for network services are defined.", domain: "Technological Controls" },
      { controlId: "A.8.22", title: "Segregation of Networks", description: "Groups of information services, users, and systems are segregated on networks.", domain: "Technological Controls" },
      { controlId: "A.8.23", title: "Web Filtering", description: "Access to external websites is managed to reduce exposure to malicious content.", domain: "Technological Controls" },
      { controlId: "A.8.24", title: "Use of Cryptography", description: "Rules for the effective use of cryptography, including key management, are defined and implemented.", domain: "Technological Controls" },
      { controlId: "A.8.25", title: "Secure Development Life Cycle", description: "Rules for the secure development of software and systems are established and applied.", domain: "Technological Controls" },
      { controlId: "A.8.26", title: "Application Security Requirements", description: "Security requirements are identified, specified, and approved when developing or acquiring applications.", domain: "Technological Controls" },
      { controlId: "A.8.27", title: "Secure System Architecture and Engineering Principles", description: "Principles for engineering secure systems are established, documented, maintained, and applied.", domain: "Technological Controls" },
      { controlId: "A.8.28", title: "Secure Coding", description: "Secure coding principles are applied to software development.", domain: "Technological Controls" },
      { controlId: "A.8.29", title: "Security Testing in Development and Acceptance", description: "Security testing is carried out during development and acceptance of new or updated systems.", domain: "Technological Controls" },
      { controlId: "A.8.30", title: "Outsourced Development", description: "The organization directs, monitors, and reviews the security of outsourced development activities.", domain: "Technological Controls" },
      { controlId: "A.8.31", title: "Separation of Development, Test and Production Environments", description: "Development, testing, and production environments are separated and secured.", domain: "Technological Controls" },
      { controlId: "A.8.32", title: "Change Management", description: "Changes are assessed, approved, implemented, and reviewed to minimize adverse impacts.", domain: "Technological Controls" },
      { controlId: "A.8.33", title: "Test Information", description: "Test data is appropriately selected, protected, and managed.", domain: "Technological Controls" },
      { controlId: "A.8.34", title: "Protection of Information Systems during Audit Testing", description: "Audit tests and assurance activities are planned and agreed with management to minimize disruption.", domain: "Technological Controls" },
    ],
  },

  "iso-27701": {
    version: "2019",
    sourceUrl: "https://www.iso.org/standard/71670.html",
    controls: [
      { controlId: "7.2.1", title: "Determine the PII Controller", description: "Determine the identity of the PII controller for the processing of PII.", domain: "Conditions for Collection and Processing" },
      { controlId: "7.2.2", title: "Identify Lawful Basis", description: "Identify and document the lawful basis for the collection and processing of PII for each purpose.", domain: "Conditions for Collection and Processing" },
      { controlId: "7.2.3", title: "Determine Purposes", description: "Determine the purposes for which PII is collected and processed before doing so.", domain: "Conditions for Collection and Processing" },
      { controlId: "7.2.4", title: "Determine Whether PII Processing Is Necessary", description: "Determine whether processing of PII is necessary to achieve the stated purpose.", domain: "Conditions for Collection and Processing" },
      { controlId: "7.2.5", title: "Determine Whether a PIA Is Necessary", description: "Determine whether a privacy impact assessment is necessary for PII processing.", domain: "Conditions for Collection and Processing" },
      { controlId: "7.2.6", title: "Identify PII Processors", description: "Identify all PII processors involved in the processing of PII.", domain: "Conditions for Collection and Processing" },
      { controlId: "7.2.7", title: "Identify Jurisdiction", description: "Identify the jurisdictions in which PII is processed and transferred.", domain: "Conditions for Collection and Processing" },
      { controlId: "7.2.8", title: "Identify Data Protection Requirements", description: "Identify all legal, statutory, regulatory, and contractual requirements for PII processing.", domain: "Conditions for Collection and Processing" },
      { controlId: "7.2.9", title: "Record Keeping", description: "Establish and maintain records of the processing of PII.", domain: "Conditions for Collection and Processing" },
      { controlId: "7.2.10", title: "Communicate PII Processing Information", description: "Provide PII principals with information about the processing of their PII.", domain: "Conditions for Collection and Processing" },
      { controlId: "7.2.11", title: "Obtain and Record Consent", description: "Obtain and record consent from PII principals where required.", domain: "Conditions for Collection and Processing" },
      { controlId: "7.2.12", title: "Apply Privacy Principles to New PII Processing", description: "Apply privacy principles when developing or using new PII processing.", domain: "Conditions for Collection and Processing" },
      { controlId: "7.2.13", title: "Use Privacy Impact Assessments", description: "Use privacy impact assessments to assess new or changed PII processing.", domain: "Conditions for Collection and Processing" },
      { controlId: "7.2.14", title: "Contract with PII Processors", description: "Establish contracts governing PII processing with PII processors.", domain: "Conditions for Collection and Processing" },
      { controlId: "7.3.1", title: "Notify PII Principals", description: "Determine and meet obligations to notify PII principals of breaches and processing activities.", domain: "Obligations to PII Principals" },
      { controlId: "7.3.2", title: "Notify Authorities", description: "Determine and meet obligations to notify relevant authorities of incidents.", domain: "Obligations to PII Principals" },
      { controlId: "7.3.3", title: "Facilitate PII Principal Rights", description: "Facilitate the exercise of PII principals' rights including access, correction, erasure, and objection.", domain: "Obligations to PII Principals" },
      { controlId: "7.3.4", title: "Enable PII Principals to Withdraw Consent", description: "Enable PII principals to withdraw consent where consent is the basis for processing.", domain: "Obligations to PII Principals" },
      { controlId: "7.3.5", title: "Enable PII Principals to Request Portability", description: "Enable PII principals to request portability of their PII where applicable.", domain: "Obligations to PII Principals" },
      { controlId: "7.4.1", title: "Limit Collection", description: "Limit the collection of PII to that which is necessary to achieve the specified purpose.", domain: "Privacy by Design and by Default" },
      { controlId: "7.4.2", title: "Correct PII", description: "Correct inaccurate or incomplete PII as required.", domain: "Privacy by Design and by Default" },
      { controlId: "7.4.3", title: "Minimize PII", description: "Minimize the amount of PII processed to the minimum necessary.", domain: "Privacy by Design and by Default" },
      { controlId: "7.4.4", title: "Store and Transfer PII Securely", description: "Store and transfer PII securely using appropriate technical controls.", domain: "Privacy by Design and by Default" },
      { controlId: "7.4.5", title: "Retain PII", description: "Retain PII only for as long as necessary to achieve the stated purpose.", domain: "Privacy by Design and by Default" },
      { controlId: "7.4.6", title: "Dispose of PII", description: "Securely dispose of PII when no longer required.", domain: "Privacy by Design and by Default" },
      { controlId: "7.5.1", title: "Identify Basis for Transfer", description: "Identify the basis for transferring PII between jurisdictions, considering legal requirements.", domain: "PII Sharing, Transfer, and Disclosure" },
      { controlId: "7.5.2", title: "Protect PII Being Transferred", description: "Protect PII being transferred to another country or region.", domain: "PII Sharing, Transfer, and Disclosure" },
      { controlId: "7.5.3", title: "Notify and Record Transfers", description: "Notify and record transfers of PII to third parties and other countries.", domain: "PII Sharing, Transfer, and Disclosure" },
      { controlId: "7.6.1", title: "Maintain Knowledge of PII Processing by Processors", description: "Maintain knowledge of the PII processing performed by PII processors.", domain: "PII Processors" },
      { controlId: "7.6.2", title: "Inform PII Principals of Processing by Processors", description: "Inform PII principals of the PII processing performed by PII processors.", domain: "PII Processors" },
      { controlId: "7.6.3", title: "Establish Obligations with Processors", description: "Establish obligations with PII processors in written agreements.", domain: "PII Processors" },
      { controlId: "7.6.4", title: "Check Processor Compliance", description: "Check compliance of PII processors with the obligations placed on them.", domain: "PII Processors" },
      { controlId: "7.6.5", title: "Determine When to Re-engage Processors", description: "Determine when to re-engage PII processors, considering risks and requirements.", domain: "PII Processors" },
      { controlId: "8.3.1", title: "Assign PII Processor Responsibilities", description: "Assign responsibilities to personnel with PII processing roles.", domain: "PII Processor Obligations" },
      { controlId: "8.4.1", title: "Provide Information to the PII Controller", description: "Provide the PII controller with the information needed to meet its obligations.", domain: "PII Processor Obligations" },
      { controlId: "8.4.2", title: "Notify the PII Controller of Breaches", description: "Notify the PII controller of a personal data breach without undue delay.", domain: "PII Processor Obligations" },
    ],
  },

  "iso-42001": {
    version: "2023",
    sourceUrl: "https://www.iso.org/standard/81230.html",
    controls: [
      { controlId: "A.2.1", title: "AI Policy", description: "Establish an AI policy aligned with other organizational policies and objectives.", domain: "Policies related to AI" },
      { controlId: "A.2.2", title: "AI Policy for Development", description: "Define policy covering the development of AI systems, including roles and responsibilities.", domain: "Policies related to AI" },
      { controlId: "A.3.1", title: "AI Risk Assessment", description: "Identify and assess risks associated with the use and development of AI systems.", domain: "Internal Organization" },
      { controlId: "A.3.2", title: "AI Risk Treatment", description: "Define and implement treatment plans for identified AI risks.", domain: "Internal Organization" },
      { controlId: "A.4.1", title: "AI Impact Assessment", description: "Assess the impacts of AI systems on individuals, groups, and society before deployment.", domain: "Resources for AI Systems" },
      { controlId: "A.4.2", title: "AI System Impact Assessment", description: "Conduct impact assessments specific to individual AI systems prior to release.", domain: "Resources for AI Systems" },
      { controlId: "A.5.1", title: "AI System Life Cycle", description: "Define and manage a life cycle for AI systems from design through retirement.", domain: "AI System Life Cycle" },
      { controlId: "A.5.2", title: "AI System Development Documentation", description: "Document AI system development decisions, including design choices and limitations.", domain: "AI System Life Cycle" },
      { controlId: "A.5.3", title: "AI System Data Quality", description: "Ensure data used in machine learning is fit for purpose and of appropriate quality.", domain: "AI System Life Cycle" },
      { controlId: "A.5.4", title: "AI System Data Provenance", description: "Document the origin, history, and provenance of data used across the AI system life cycle.", domain: "AI System Life Cycle" },
      { controlId: "A.5.5", title: "AI System Documentation", description: "Produce and maintain documentation describing the AI system's design, function, and use.", domain: "AI System Life Cycle" },
      { controlId: "A.5.6", title: "AI System Transparency", description: "Communicate information about the AI system's use, capabilities, and limitations to relevant parties.", domain: "AI System Life Cycle" },
      { controlId: "A.6.1", title: "AI System Operation", description: "Operate AI systems in accordance with documented procedures and policies.", domain: "AI System Deployment and Operation" },
      { controlId: "A.6.2", title: "AI System Interaction", description: "Design and manage interactions between the AI system and users and other parties.", domain: "AI System Deployment and Operation" },
      { controlId: "A.6.3", title: "AI System Monitoring", description: "Monitor AI systems to detect anomalies, failures, and deviations from intended behavior.", domain: "AI System Deployment and Operation" },
      { controlId: "A.7.1", title: "AI System Change Management", description: "Assess, approve, and control changes to AI systems to avoid unintended consequences.", domain: "AI System Change Management" },
      { controlId: "A.8.1", title: "AI System Information Sharing", description: "Share information about AI systems and their risks with relevant parties as appropriate.", domain: "AI System Information Sharing" },
      { controlId: "A.9.1", title: "Use of AI Systems by Third Parties", description: "Manage risks from AI systems provided by or used by third parties.", domain: "Use of AI Systems" },
      { controlId: "A.9.2", title: "Use of AI Systems within the Organization", description: "Manage the internal use of AI systems, including impact and risk assessment.", domain: "Use of AI Systems" },
      { controlId: "A.9.3", title: "Use of AI Systems by Customers", description: "Manage the use of AI systems by customers and external parties.", domain: "Use of AI Systems" },
      { controlId: "A.10.1", title: "AI System Internal Audit", description: "Conduct internal audits of the AI management system at planned intervals.", domain: "Monitoring and Measurement of AI Systems" },
      { controlId: "A.11.1", title: "Acquisition of AI Systems", description: "Apply security and management requirements when acquiring AI systems.", domain: "AI System Acquisition" },
    ],
  },

  "iso-27019": {
    version: "2017",
    sourceUrl: "https://www.iso.org/standard/68091.html",
    controls: [
      { controlId: "A.5.1", title: "Policies for Information Security in Process Control", description: "Information security policy addresses process control and OT environments in the energy industry.", domain: "Organizational Controls" },
      { controlId: "A.5.9", title: "Inventory of OT Assets", description: "Maintain an inventory of process control system assets and field devices.", domain: "Organizational Controls" },
      { controlId: "A.5.10", title: "Acceptable Use of Process Control Assets", description: "Define rules for the acceptable use of process control systems and their data.", domain: "Organizational Controls" },
      { controlId: "A.5.15", title: "Access Control to Process Control Systems", description: "Control logical and physical access to process control systems consistent with operational requirements.", domain: "Organizational Controls" },
      { controlId: "A.5.19", title: "Information Security in Supplier Relationships", description: "Manage security risks from suppliers of process control systems and services.", domain: "Organizational Controls" },
      { controlId: "A.5.24", title: "Incident Management in OT", description: "Plan and prepare for information security incidents affecting process control systems.", domain: "Organizational Controls" },
      { controlId: "A.6.7", title: "Remote Working for OT Personnel", description: "Secure remote access to process control systems and OT networks.", domain: "People Controls" },
      { controlId: "A.7.1", title: "Physical Security Perimeters for OT", description: "Define security perimeters around process control facilities and control rooms.", domain: "Physical Controls" },
      { controlId: "A.7.2", title: "Physical Entry to Process Control Areas", description: "Control physical entry to process control and substation areas.", domain: "Physical Controls" },
      { controlId: "A.7.8", title: "Equipment Siting and Protection", description: "Site process control equipment to protect against environmental and physical threats.", domain: "Physical Controls" },
      { controlId: "A.8.1", title: "User Endpoint Devices in OT", description: "Protect endpoints used to access or operate process control systems.", domain: "Technological Controls" },
      { controlId: "A.8.2", title: "Privileged Access to OT Systems", description: "Restrict and manage privileged access to process control and field systems.", domain: "Technological Controls" },
      { controlId: "A.8.5", title: "Secure Authentication for OT", description: "Implement secure authentication for access to process control systems.", domain: "Technological Controls" },
      { controlId: "A.8.6", title: "Capacity Management for Process Control", description: "Monitor and manage capacity of process control networks and systems.", domain: "Technological Controls" },
      { controlId: "A.8.7", title: "Malware Protection for OT", description: "Implement malware protection suitable for process control environments.", domain: "Technological Controls" },
      { controlId: "A.8.8", title: "Management of Technical Vulnerabilities in OT", description: "Manage technical vulnerabilities of process control systems, considering availability constraints.", domain: "Technological Controls" },
      { controlId: "A.8.9", title: "Configuration Management of OT", description: "Establish and manage configurations of process control systems and field devices.", domain: "Technological Controls" },
      { controlId: "A.8.13", title: "Information Backup for OT", description: "Maintain and test backup copies of process control data and configurations.", domain: "Technological Controls" },
      { controlId: "A.8.14", title: "Redundancy of Process Control Facilities", description: "Provide redundancy for critical process control information processing facilities.", domain: "Technological Controls" },
      { controlId: "A.8.15", title: "Logging for Process Control", description: "Produce, store, protect, and analyze logs of process control system activity.", domain: "Technological Controls" },
      { controlId: "A.8.16", title: "Monitoring Activities in OT", description: "Monitor process control systems and OT networks to detect anomalies and potential security events.", domain: "Technological Controls" },
      { controlId: "A.8.19", title: "Installation of Software on Operational Systems", description: "Control the installation of software, including patches, on operational process control systems.", domain: "Technological Controls" },
      { controlId: "A.8.20", title: "Networks Security for OT", description: "Secure and segment process control networks, including separation from business networks.", domain: "Technological Controls" },
      { controlId: "A.8.22", title: "Segregation of Networks", description: "Separate process control networks from corporate networks and segment OT zones.", domain: "Technological Controls" },
      { controlId: "A.8.24", title: "Use of Cryptography in OT", description: "Use cryptography where applicable to protect data in process control systems.", domain: "Technological Controls" },
      { controlId: "A.8.32", title: "Change Management for OT", description: "Assess, approve, and control changes to process control systems and field devices.", domain: "Technological Controls" },
      { controlId: "A.8.34", title: "Audit Testing of Process Control Systems", description: "Plan and agree audits and tests of process control systems to minimize disruption to operations.", domain: "Technological Controls" },
    ],
  },

  "iso-27017": {
    version: "2015",
    sourceUrl: "https://www.iso.org/standard/43757.html",
    controls: [
      { controlId: "5.1.1", title: "Policies for Information Security in Cloud Services", description: "Cloud customers and providers define information security policy specific to cloud services.", domain: "General Controls" },
      { controlId: "5.1.2", title: "Roles and Responsibilities in Cloud", description: "Define and agree roles and responsibilities between cloud customer and provider.", domain: "General Controls" },
      { controlId: "5.1.3", title: "Segregation of Duties in Cloud", description: "Separate conflicting duties between cloud customer and provider personnel.", domain: "General Controls" },
      { controlId: "5.1.4", title: "Cloud Service Documentation", description: "Produce and maintain documentation of the cloud service, its architecture, and controls.", domain: "General Controls" },
      { controlId: "5.1.5", title: "Contractual Agreements for Cloud", description: "Establish contracts specifying the security requirements for the cloud service.", domain: "General Controls" },
      { controlId: "5.1.6", title: "Information Security in the Use of Cloud Services", description: "Manage information security within the cloud customer's use of the service.", domain: "General Controls" },
      { controlId: "5.1.7", title: "Cloud Service Security Management", description: "Coordinate and manage security activities between cloud customer and provider.", domain: "General Controls" },
      { controlId: "5.2.1", title: "Classification of Information in Cloud", description: "Classify cloud-hosted information according to the customer's classification scheme.", domain: "Asset Management" },
      { controlId: "5.2.2", title: "Return of Assets from Cloud", description: "Ensure cloud customer assets and data are returned on termination of the service.", domain: "Asset Management" },
      { controlId: "5.3.1", title: "Vetting of Cloud Provider Personnel", description: "Cloud provider screens personnel with access to customer environments.", domain: "Human Resource Security" },
      { controlId: "5.3.2", title: "Cloud Provider Personnel Termination", description: "Revoke cloud provider personnel access upon termination of employment.", domain: "Human Resource Security" },
      { controlId: "5.4.1", title: "Physical Security in Cloud Sites", description: "Protect physical facilities hosting cloud services with appropriate controls.", domain: "Physical and Environmental Security" },
      { controlId: "5.4.2", title: "Physical Access to Cloud Premises", description: "Control physical access to premises hosting cloud infrastructure.", domain: "Physical and Environmental Security" },
      { controlId: "5.5.1", title: "Logical and Virtual Network Separation", description: "Separate virtual networks and workloads using logical isolation mechanisms.", domain: "Operations Management" },
      { controlId: "5.5.2", title: "Cloud Administrator Operations", description: "Apply privileged access management to cloud administrators.", domain: "Operations Management" },
      { controlId: "5.5.3", title: "Monitoring and Reporting of Cloud Services", description: "Monitor cloud service operation and report to the cloud customer.", domain: "Operations Management" },
      { controlId: "5.5.4", title: "Virtual and Physical Network Security", description: "Implement network security controls in the cloud environment, including firewalls and segmentation.", domain: "Operations Management" },
      { controlId: "5.5.5", title: "Cloud Service Change Management", description: "Manage changes to the cloud service with customer notification and approval.", domain: "Operations Management" },
      { controlId: "5.5.6", title: "Cloud Capacity and Performance Management", description: "Manage capacity and performance of cloud services to meet commitments.", domain: "Operations Management" },
      { controlId: "5.5.7", title: "Cloud Service Backup", description: "Back up cloud data and configurations consistent with agreed retention.", domain: "Operations Management" },
      { controlId: "5.5.8", title: "Logging and Monitoring in Cloud", description: "Collect and analyze logs from cloud services and infrastructure.", domain: "Operations Management" },
      { controlId: "5.6.1", title: "Cloud Service Incident Management", description: "Establish incident response processes covering cloud services.", domain: "Operations Management" },
      { controlId: "5.7.1", title: "Secure Administrative Interfaces", description: "Protect administrative interfaces to cloud services with strong authentication.", domain: "Access Control" },
      { controlId: "5.7.2", title: "Cloud User Access Management", description: "Manage access rights of cloud users, including provisioning and revocation.", domain: "Access Control" },
      { controlId: "5.7.3", title: "Customer Environment Isolation", description: "Ensure isolation between customers' environments and data in the cloud.", domain: "Access Control" },
      { controlId: "5.8.1", title: "Cloud Cryptographic Controls", description: "Use cryptography to protect cloud data at rest and in transit.", domain: "Cryptography" },
      { controlId: "5.8.2", title: "Cloud Data Remanence Prevention", description: "Prevent data remanence when cloud storage is released or reallocated.", domain: "Cryptography" },
      { controlId: "5.9.1", title: "Security of Cloud Supply Chain", description: "Manage security risks in the cloud provider's own supply chain.", domain: "Supplier Relationships" },
      { controlId: "5.9.2", title: "Cloud Service Delivery Monitoring", description: "Monitor the delivery of the cloud service against the agreed service levels.", domain: "Supplier Relationships" },
      { controlId: "5.10.1", title: "Cloud Service Audit Rights", description: "Grant cloud customers audit and assessment rights over the service.", domain: "Compliance" },
      { controlId: "5.10.2", title: "Cloud Service Compliance", description: "Ensure the cloud service meets applicable legal and regulatory requirements.", domain: "Compliance" },
      { controlId: "5.10.3", title: "Cloud Service Data Protection", description: "Protect personal data processed in the cloud in line with applicable law.", domain: "Compliance" },
      { controlId: "5.10.4", title: "Cloud Service Security Testing", description: "Conduct security testing of the cloud service with agreed scope and safeguards.", domain: "Compliance" },
    ],
  },

  "iso-27018": {
    version: "2019",
    sourceUrl: "https://www.iso.org/standard/76559.html",
    controls: [
      { controlId: "6.1", title: "Cloud PII Processor Roles and Responsibilities", description: "Define the roles and responsibilities of the cloud service provider as a PII processor.", domain: "Cloud PII Processing" },
      { controlId: "6.2", title: "Cloud PII Processor Policies", description: "Establish policies governing the processing of PII in public cloud services.", domain: "Cloud PII Processing" },
      { controlId: "6.3", title: "Return, Transfer, and Disposal of Personal Data", description: "Return, transfer, or dispose of PII upon the customer's request or end of service.", domain: "Cloud PII Processing" },
      { controlId: "6.4", title: "Cloud Provider Training and Awareness", description: "Train cloud provider personnel on PII protection obligations.", domain: "Cloud PII Processing" },
      { controlId: "6.5", title: "Secure Storage of PII", description: "Store PII in cloud services with appropriate technical controls and segregation.", domain: "Cloud PII Processing" },
      { controlId: "6.6", title: "Cloud Provider Security", description: "Implement security controls in the cloud environment to protect PII.", domain: "Cloud PII Processing" },
      { controlId: "6.7", title: "Restrict Access to PII", description: "Restrict access to PII to authorized personnel on a least-privilege basis.", domain: "Cloud PII Processing" },
      { controlId: "6.8", title: "Cloud Logging and Monitoring of PII", description: "Log access and processing of PII in the cloud and make logs available to the customer.", domain: "Cloud PII Processing" },
      { controlId: "6.9", title: "Customer Notification of PII Incidents", description: "Notify the cloud customer of any unauthorized access, use, or disclosure of PII.", domain: "Cloud PII Processing" },
      { controlId: "6.10", title: "Assist Customer with PII Principal Rights", description: "Support the cloud customer in fulfilling PII principals' rights.", domain: "Cloud PII Processing" },
      { controlId: "6.11", title: "Assist Customer with Compliance", description: "Assist the cloud customer in meeting its regulatory compliance obligations.", domain: "Cloud PII Processing" },
      { controlId: "6.12", title: "Assist Customer with Assessments", description: "Support the cloud customer's privacy assessments and audits of the service.", domain: "Cloud PII Processing" },
      { controlId: "6.13", title: "Use of Subcontractors", description: "Only engage subcontractors with appropriate contractual and security obligations for PII.", domain: "Cloud PII Processing" },
      { controlId: "6.14", title: "Minimize and Anonymize PII", description: "Minimize and anonymize PII where feasible to reduce privacy risk.", domain: "Cloud PII Processing" },
      { controlId: "6.15", title: "Restrictions on Customer Use of PII", description: "Restrict the cloud customer's use of PII to the agreed purposes.", domain: "Cloud PII Processing" },
      { controlId: "6.16", title: "Geographic Location of PII", description: "Advise the customer of the geographic locations where PII is stored or processed.", domain: "Cloud PII Processing" },
      { controlId: "6.17", title: "Cloud PII Retention", description: "Establish and honor PII retention and disposal requirements.", domain: "Cloud PII Processing" },
      { controlId: "6.18", title: "Cloud Provider Disclosures", description: "Disclose information about the cloud service's PII processing practices.", domain: "Cloud PII Processing" },
    ],
  },

  "iso-22301": {
    version: "2019",
    sourceUrl: "https://www.iso.org/standard/75106.html",
    controls: [
      { controlId: "4.1", title: "Understanding the Organization and Its Context", description: "Determine the external and internal issues relevant to the BCMS's purpose.", domain: "Context of the Organization" },
      { controlId: "4.2", title: "Needs and Expectations of Interested Parties", description: "Determine interested parties relevant to the BCMS and their requirements.", domain: "Context of the Organization" },
      { controlId: "4.4", title: "Business Continuity Management System", description: "Establish, implement, maintain, and continually improve a BCMS.", domain: "Context of the Organization" },
      { controlId: "5.1", title: "Leadership and Commitment", description: "Top management demonstrates leadership and commitment to the BCMS.", domain: "Leadership" },
      { controlId: "5.2", title: "Business Continuity Policy", description: "Establish a business continuity policy appropriate to the organization's purpose.", domain: "Leadership" },
      { controlId: "5.3", title: "Roles, Responsibilities, and Authorities", description: "Assign roles, responsibilities, and authorities for the BCMS.", domain: "Leadership" },
      { controlId: "6.1", title: "Actions to Address Risks and Opportunities", description: "Determine risks and opportunities for the BCMS and plan actions to address them.", domain: "Planning" },
      { controlId: "6.2", title: "Business Continuity Objectives", description: "Establish business continuity objectives consistent with the policy.", domain: "Planning" },
      { controlId: "7.1", title: "Resources", description: "Determine and provide resources needed for the BCMS.", domain: "Support" },
      { controlId: "7.2", title: "Competence", description: "Ensure personnel are competent to perform BCMS roles.", domain: "Support" },
      { controlId: "7.3", title: "Awareness", description: "Ensure personnel are aware of the BCMS policy and their contribution to it.", domain: "Support" },
      { controlId: "7.4", title: "Communication", description: "Determine and implement internal and external communication for the BCMS.", domain: "Support" },
      { controlId: "7.5", title: "Documented Information", description: "Control documented information required by the BCMS.", domain: "Support" },
      { controlId: "8.1", title: "Operational Planning and Control", description: "Plan, implement, and control the processes needed to meet BCMS requirements.", domain: "Operation" },
      { controlId: "8.2", title: "Business Impact Analysis", description: "Assess the impacts of disruptions to the organization's prioritized activities.", domain: "Operation" },
      { controlId: "8.3", title: "Risk Assessment", description: "Assess the risks of disruption to prioritized activities and determine risk treatments.", domain: "Operation" },
      { controlId: "8.4", title: "Business Continuity Strategies and Solutions", description: "Determine and select business continuity strategies and solutions.", domain: "Operation" },
      { controlId: "8.4.4", title: "Business Continuity Procedures", description: "Develop, document, and implement procedures to respond to disruptions.", domain: "Operation" },
      { controlId: "8.5", title: "Exercise and Testing", description: "Exercise and test the BCMS and business continuity arrangements at planned intervals.", domain: "Operation" },
      { controlId: "9.1", title: "Monitoring, Measurement, Analysis, and Evaluation", description: "Monitor, measure, analyze, and evaluate the performance of the BCMS.", domain: "Performance Evaluation" },
      { controlId: "9.2", title: "Internal Audit", description: "Conduct internal audits of the BCMS at planned intervals.", domain: "Performance Evaluation" },
      { controlId: "9.3", title: "Management Review", description: "Top management reviews the BCMS at planned intervals.", domain: "Performance Evaluation" },
      { controlId: "10.1", title: "Nonconformity and Corrective Action", description: "Take corrective action in response to nonconformities.", domain: "Improvement" },
      { controlId: "10.2", title: "Continual Improvement", description: "Continually improve the suitability, adequacy, and effectiveness of the BCMS.", domain: "Improvement" },
    ],
  },

  "iso-9001": {
    version: "2015",
    sourceUrl: "https://www.iso.org/standard/62085.html",
    controls: [
      { controlId: "4.1", title: "Understanding the Organization and Its Context", description: "Determine external and internal issues relevant to the QMS's purpose.", domain: "Context of the Organization" },
      { controlId: "4.2", title: "Understanding Needs and Expectations of Interested Parties", description: "Determine interested parties and their requirements relevant to the QMS.", domain: "Context of the Organization" },
      { controlId: "4.4", title: "Quality Management System and Its Processes", description: "Establish, implement, maintain, and continually improve the QMS and its processes.", domain: "Context of the Organization" },
      { controlId: "5.1", title: "Leadership and Commitment", description: "Top management demonstrates leadership and commitment to the QMS.", domain: "Leadership" },
      { controlId: "5.2", title: "Quality Policy", description: "Establish a quality policy appropriate to the organization's purpose.", domain: "Leadership" },
      { controlId: "5.3", title: "Organizational Roles, Responsibilities, and Authorities", description: "Assign roles, responsibilities, and authorities for the QMS.", domain: "Leadership" },
      { controlId: "6.1", title: "Actions to Address Risks and Opportunities", description: "Determine risks and opportunities and plan actions to address them.", domain: "Planning" },
      { controlId: "6.2", title: "Quality Objectives", description: "Establish quality objectives at relevant functions, levels, and processes.", domain: "Planning" },
      { controlId: "7.1", title: "Resources", description: "Provide the resources needed to establish, implement, and maintain the QMS.", domain: "Support" },
      { controlId: "7.2", title: "Competence", description: "Ensure personnel are competent on the basis of education, training, and experience.", domain: "Support" },
      { controlId: "7.3", title: "Awareness", description: "Ensure personnel are aware of the quality policy and their contribution to QMS effectiveness.", domain: "Support" },
      { controlId: "7.4", title: "Communication", description: "Determine internal and external communications relevant to the QMS.", domain: "Support" },
      { controlId: "7.5", title: "Documented Information", description: "Create, update, and control documented information required by the QMS.", domain: "Support" },
      { controlId: "8.1", title: "Operational Planning and Control", description: "Plan, implement, and control the processes needed to meet product and service requirements.", domain: "Operation" },
      { controlId: "8.2", title: "Requirements for Products and Services", description: "Determine, review, and communicate requirements for products and services.", domain: "Operation" },
      { controlId: "8.3", title: "Design and Development of Products and Services", description: "Control design and development processes to ensure products and services meet requirements.", domain: "Operation" },
      { controlId: "8.4", title: "Control of Externally Provided Processes, Products, and Services", description: "Ensure externally provided processes, products, and services conform to requirements.", domain: "Operation" },
      { controlId: "8.5", title: "Production and Service Provision", description: "Produce products and provide services under controlled conditions.", domain: "Operation" },
      { controlId: "8.6", title: "Release of Products and Services", description: "Release products and services only when acceptance criteria have been met.", domain: "Operation" },
      { controlId: "8.7", title: "Control of Nonconforming Outputs", description: "Identify and control outputs that do not conform to requirements.", domain: "Operation" },
      { controlId: "9.1", title: "Monitoring, Measurement, Analysis, and Evaluation", description: "Monitor, measure, analyze, and evaluate the QMS and its processes.", domain: "Performance Evaluation" },
      { controlId: "9.2", title: "Internal Audit", description: "Conduct internal audits at planned intervals to determine conformity.", domain: "Performance Evaluation" },
      { controlId: "9.3", title: "Management Review", description: "Top management reviews the QMS at planned intervals.", domain: "Performance Evaluation" },
      { controlId: "10.1", title: "Nonconformity and Corrective Action", description: "Take corrective action in response to nonconformities.", domain: "Improvement" },
      { controlId: "10.2", title: "Continual Improvement", description: "Continually improve the suitability, adequacy, and effectiveness of the QMS.", domain: "Improvement" },
    ],
  },
};
