import type { Catalog } from "./index";

export const privacyCatalogs: Record<string, Catalog> = {
  gdpr: {
    version: "2016/679",
    sourceUrl: "https://gdpr-info.eu/",
    controls: [
      { controlId: "Art. 1", title: "Subject Matter and Objectives", description: "Protect fundamental rights and freedoms of natural persons, in particular the right to personal data protection.", domain: "General Provisions" },
      { controlId: "Art. 2", title: "Material Scope", description: "Applies to the processing of personal data wholly or partly by automated means and non-automated means forming part of a filing system.", domain: "General Provisions" },
      { controlId: "Art. 3", title: "Territorial Scope", description: "Applies to processing in the EU and to processing of EU data subjects by controllers or processors outside the EU.", domain: "General Provisions" },
      { controlId: "Art. 4", title: "Definitions", description: "Defines key terms including personal data, processing, controller, processor, consent, and data subject.", domain: "General Provisions" },
      { controlId: "Art. 5", title: "Principles Relating to Processing of Personal Data", description: "Process personal data lawfully, fairly, transparently, purpose-limited, minimized, accurate, storage-limited, and securely.", domain: "Principles" },
      { controlId: "Art. 6", title: "Lawfulness of Processing", description: "Processing is lawful only where at least one lawful basis applies, including consent, contract, legal obligation, vital interests, public interest, or legitimate interests.", domain: "Principles" },
      { controlId: "Art. 7", title: "Conditions for Consent", description: "Demonstrate consent was freely given, specific, informed, and unambiguous, and make withdrawal as easy as granting.", domain: "Principles" },
      { controlId: "Art. 8", title: "Conditions Applicable to Child's Consent", description: "For online services offered to children, consent is only valid with parental authority when the child is below 16 (or lower, but not below 13).", domain: "Principles" },
      { controlId: "Art. 9", title: "Processing of Special Categories of Personal Data", description: "Prohibit processing of sensitive data unless an explicit exception applies.", domain: "Principles" },
      { controlId: "Art. 10", title: "Processing of Personal Data Relating to Criminal Convictions", description: "Processing of criminal data is only permitted under official authority or another lawful basis.", domain: "Principles" },
      { controlId: "Art. 11", title: "Processing Not Requiring Identification", description: "Where the controller cannot identify the data subject, it is not obliged to maintain identification information.", domain: "Principles" },
      { controlId: "Art. 12", title: "Transparent Information and Communication", description: "Provide information to data subjects in a concise, transparent, intelligible, and easily accessible form.", domain: "Rights of the Data Subject" },
      { controlId: "Art. 13", title: "Information to Be Provided When Collecting Personal Data", description: "Provide the controller's identity, purposes, legal basis, retention, and data subject rights when collecting data.", domain: "Rights of the Data Subject" },
      { controlId: "Art. 14", title: "Information Where Data Have Not Been Obtained from the Data Subject", description: "Provide equivalent information when data is obtained from another source, within a reasonable period.", domain: "Rights of the Data Subject" },
      { controlId: "Art. 15", title: "Right of Access", description: "Provide data subjects with a copy of their personal data and information about processing.", domain: "Rights of the Data Subject" },
      { controlId: "Art. 16", title: "Right to Rectification", description: "Enable data subjects to have inaccurate personal data corrected without undue delay.", domain: "Rights of the Data Subject" },
      { controlId: "Art. 17", title: "Right to Erasure (Right to Be Forgotten)", description: "Erase personal data without undue delay where grounds apply, including withdrawal of consent and unlawful processing.", domain: "Rights of the Data Subject" },
      { controlId: "Art. 18", title: "Right to Restriction of Processing", description: "Restrict processing where accuracy is contested, processing is unlawful, or the controller no longer needs the data.", domain: "Rights of the Data Subject" },
      { controlId: "Art. 19", title: "Notification Obligation Regarding Rectification, Erasure, or Restriction", description: "Communicate rectification, erasure, or restriction to each recipient to whom the data was disclosed.", domain: "Rights of the Data Subject" },
      { controlId: "Art. 20", title: "Right to Data Portability", description: "Provide personal data in a structured, commonly used, machine-readable format upon request.", domain: "Rights of the Data Subject" },
      { controlId: "Art. 21", title: "Right to Object", description: "Allow data subjects to object to processing based on legitimate interests, direct marketing, or profiling.", domain: "Rights of the Data Subject" },
      { controlId: "Art. 22", title: "Automated Individual Decision-Making, Including Profiling", description: "Do not subject data subjects to decisions based solely on automated processing with legal or significant effects, subject to exceptions.", domain: "Rights of the Data Subject" },
      { controlId: "Art. 23", title: "Restrictions", description: "Legal restrictions on the rights in Articles 12-22 must respect the essence of fundamental rights.", domain: "Rights of the Data Subject" },
      { controlId: "Art. 24", title: "Responsibility of the Controller", description: "Implement appropriate technical and organizational measures to ensure and demonstrate compliance.", domain: "Controller and Processor" },
      { controlId: "Art. 25", title: "Data Protection by Design and by Default", description: "Implement data protection principles by design and ensure processing by default only processes necessary data.", domain: "Controller and Processor" },
      { controlId: "Art. 26", title: "Joint Controllers", description: "Joint controllers define their responsibilities transparently and provide data subjects with relevant information.", domain: "Controller and Processor" },
      { controlId: "Art. 27", title: "Representatives of Controllers or Processors Not Established in the Union", description: "Non-EU controllers or processors must designate a representative in the EU where processing targets EU data subjects.", domain: "Controller and Processor" },
      { controlId: "Art. 28", title: "Processor", description: "Processors act only on documented instructions and provide sufficient guarantees through binding contracts.", domain: "Controller and Processor" },
      { controlId: "Art. 29", title: "Processing under the Authority of the Controller or Processor", description: "Persons acting under the controller's authority process data only on documented instructions.", domain: "Controller and Processor" },
      { controlId: "Art. 30", title: "Records of Processing Activities", description: "Maintain records of all processing activities, including purposes, categories, recipients, and transfers.", domain: "Controller and Processor" },
      { controlId: "Art. 32", title: "Security of Processing", description: "Implement appropriate technical and organizational measures to ensure a level of security appropriate to the risk.", domain: "Controller and Processor" },
      { controlId: "Art. 33", title: "Notification of a Personal Data Breach to the Supervisory Authority", description: "Notify the supervisory authority of a personal data breach within 72 hours of becoming aware.", domain: "Controller and Processor" },
      { controlId: "Art. 34", title: "Communication of a Personal Data Breach to the Data Subject", description: "Communicate a high-risk breach to data subjects without undue delay.", domain: "Controller and Processor" },
      { controlId: "Art. 35", title: "Data Protection Impact Assessment", description: "Carry out a DPIA where processing is likely to result in a high risk to rights and freedoms.", domain: "Controller and Processor" },
      { controlId: "Art. 36", title: "Prior Consultation", description: "Consult the supervisory authority before processing when a DPIA indicates a high residual risk.", domain: "Controller and Processor" },
      { controlId: "Art. 37", title: "Designation of the Data Protection Officer", description: "Designate a DPO where required by the nature or scope of processing.", domain: "Controller and Processor" },
      { controlId: "Art. 38", title: "Position of the Data Protection Officer", description: "Ensure the DPO is involved properly and independently in all data protection issues.", domain: "Controller and Processor" },
      { controlId: "Art. 39", title: "Tasks of the Data Protection Officer", description: "The DPO informs, advises, monitors compliance, and cooperates with the supervisory authority.", domain: "Controller and Processor" },
      { controlId: "Art. 40", title: "Codes of Conduct", description: "Encourage the drawing up of codes of conduct to demonstrate compliance.", domain: "Controller and Processor" },
      { controlId: "Art. 41", title: "Monitoring of Approved Codes of Conduct", description: "Monitor compliance with approved codes of conduct.", domain: "Controller and Processor" },
      { controlId: "Art. 42", title: "Certification", description: "Establish certification mechanisms, seals, and marks to demonstrate compliance.", domain: "Controller and Processor" },
      { controlId: "Art. 43", title: "Certification Bodies", description: "Accredit certification bodies to issue and withdraw data protection certifications.", domain: "Controller and Processor" },
      { controlId: "Art. 44", title: "General Principle for Transfers", description: "Personal data may only be transferred outside the EU where conditions in Chapter V are complied with.", domain: "Transfers" },
      { controlId: "Art. 45", title: "Transfers on the Basis of an Adequacy Decision", description: "Transfer data to third countries that the Commission has found to ensure an adequate level of protection.", domain: "Transfers" },
      { controlId: "Art. 46", title: "Transfers Subject to Appropriate Safeguards", description: "Transfer data using appropriate safeguards such as standard contractual clauses or binding corporate rules.", domain: "Transfers" },
      { controlId: "Art. 47", title: "Binding Corporate Rules", description: "Use binding corporate rules approved by the supervisory authority for intra-group transfers.", domain: "Transfers" },
      { controlId: "Art. 49", title: "Derogations for Specific Situations", description: "Transfer data under specified derogations, including explicit consent and contractual necessity.", domain: "Transfers" },
      { controlId: "Art. 77", title: "Right to Lodge a Complaint with a Supervisory Authority", description: "Allow data subjects to lodge complaints with a supervisory authority.", domain: "Remedies and Penalties" },
      { controlId: "Art. 82", title: "Right to Compensation", description: "Compensate data subjects for damage caused by infringements of the Regulation.", domain: "Remedies and Penalties" },
      { controlId: "Art. 83", title: "General Conditions for Imposing Administrative Fines", description: "Impose effective, proportionate, and dissuasive fines, up to 4% of turnover for serious infringements.", domain: "Remedies and Penalties" },
    ],
  },

  ccpa: {
    version: "CPRA 2023",
    sourceUrl: "https://cppa.ca.gov/regulations/",
    controls: [
      { controlId: "1798.100", title: "Right to Know", description: "Provide consumers with the right to know the categories and specific pieces of personal information collected.", domain: "Consumer Rights" },
      { controlId: "1798.106", title: "Right to Correct", description: "Provide consumers the right to correct inaccurate personal information.", domain: "Consumer Rights" },
      { controlId: "1798.105", title: "Right to Delete", description: "Provide consumers the right to request deletion of their personal information.", domain: "Consumer Rights" },
      { controlId: "1798.110", title: "Right to Access and Portability", description: "Provide consumers the right to obtain their personal information in a portable, usable format.", domain: "Consumer Rights" },
      { controlId: "1798.120", title: "Right to Opt-Out of Sale or Sharing", description: "Provide consumers the right to opt out of the sale or sharing of their personal information.", domain: "Consumer Rights" },
      { controlId: "1798.121", title: "Right to Limit Use of Sensitive Personal Information", description: "Provide consumers the right to limit the use of sensitive personal information to essential purposes.", domain: "Consumer Rights" },
      { controlId: "1798.130", title: "Privacy Notice Disclosure", description: "Provide a privacy notice describing categories of data collected, sold, shared, and the purposes of use.", domain: "Notice and Disclosure" },
      { controlId: "1798.135", title: "Do Not Sell or Share My Personal Information Link", description: "Provide a clear 'Do Not Sell or Share My Personal Information' link on the homepage.", domain: "Notice and Disclosure" },
      { controlId: "1798.125", title: "Non-Discrimination", description: "Do not discriminate against consumers who exercise their privacy rights.", domain: "Nondiscrimination" },
      { controlId: "1798.140", title: "Service Provider and Contractor Contracts", description: "Contractually restrict service providers and contractors from selling or sharing personal information.", domain: "Business Obligations" },
      { controlId: "1798.148", title: "Automated Decision-Making", description: "Provide consumers the right to opt out of automated decision-making technology producing legally significant effects.", domain: "Consumer Rights" },
      { controlId: "1798.155", title: "Children's Privacy", description: "Do not sell or share personal information of consumers under 16 without affirmative authorization, and under 13 without parental consent.", domain: "Business Obligations" },
      { controlId: "1798.150", title: "Private Right of Action for Data Breach", description: "Maintain reasonable security practices to avoid statutory damages in breach lawsuits.", domain: "Security" },
      { controlId: "1798.185", title: "Regulatory Compliance and Enforcement", description: "Comply with regulations promulgated by the California Privacy Protection Agency.", domain: "Business Obligations" },
      { controlId: "1798.199.90", title: "Annual Risk Assessment", description: "Conduct an annual cybersecurity and privacy risk assessment of processing that presents significant risk.", domain: "Business Obligations" },
      { controlId: "1798.199.95", title: "Cybersecurity Audits", description: "Conduct annual cybersecurity audits of processing that presents significant risk.", domain: "Business Obligations" },
    ],
  },

  pipeda: {
    version: "2022",
    sourceUrl: "https://www.priv.gc.ca/en/privacy-topics/privacy-laws-in-canada/02_05_d_15/",
    controls: [
      { controlId: "S.5", title: "Accountability", description: "An organization is responsible for personal information under its control and must designate an individual accountable for compliance.", domain: "Fair Information Principles" },
      { controlId: "S.5(3)", title: "Accountable Officer", description: "Identify the individual(s) accountable for the organization's compliance with privacy obligations.", domain: "Fair Information Principles" },
      { controlId: "S.6", title: "Identifying Purposes", description: "Identify the purposes for which personal information is collected before or at the time of collection.", domain: "Fair Information Principles" },
      { controlId: "S.7", title: "Consent", description: "Obtain knowledge and consent of the individual for the collection, use, or disclosure of personal information, subject to exceptions.", domain: "Fair Information Principles" },
      { controlId: "S.8", title: "Limiting Collection", description: "Limit collection of personal information to that which is necessary for the identified purposes.", domain: "Fair Information Principles" },
      { controlId: "S.9", title: "Limiting Use, Disclosure, and Retention", description: "Use, disclose, and retain personal information only for the identified purposes and no longer than necessary.", domain: "Fair Information Principles" },
      { controlId: "S.10", title: "Accuracy", description: "Keep personal information that is used on an ongoing basis accurate, complete, and up to date.", domain: "Fair Information Principles" },
      { controlId: "S.11", title: "Safeguards", description: "Protect personal information with security safeguards appropriate to the sensitivity of the information.", domain: "Fair Information Principles" },
      { controlId: "S.12", title: "Openness", description: "Make information about policies and practices relating to personal information readily available.", domain: "Fair Information Principles" },
      { controlId: "S.13", title: "Individual Access", description: "Upon request, inform individuals of the existence, use, and disclosure of their personal information and provide access.", domain: "Fair Information Principles" },
      { controlId: "S.14", title: "Challenging Compliance", description: "Provide procedures for individuals to challenge an organization's compliance with the principles.", domain: "Fair Information Principles" },
      { controlId: "S.10.1", title: "Cross-Border Transfer Safeguards", description: "Transfer personal information across borders using contractual or other means to ensure comparable protection.", domain: "Cross-Border" },
      { controlId: "S.10.2", title: "Breach Notification", description: "Report privacy breaches that pose a real risk of significant harm to affected individuals and the Privacy Commissioner.", domain: "Breach Management" },
    ],
  },

  lgpd: {
    version: "2019/13709",
    sourceUrl: "https://www.gov.br/cidadania/pt-br/lgpd",
    controls: [
      { controlId: "Art. 6", title: "Principles", description: "Process personal data in accordance with principles of purpose, adequacy, necessity, free access, quality, transparency, security, prevention, non-discrimination, and accountability.", domain: "Principles" },
      { controlId: "Art. 7", title: "Legal Bases for Processing", description: "Process personal data only under a lawful basis, including consent, legal obligation, contract, legal proceedings, vital interests, or legitimate interests.", domain: "Legal Bases" },
      { controlId: "Art. 8", title: "Consent", description: "Obtain free, informed, and unambiguous consent that is documented and can be revoked at any time.", domain: "Legal Bases" },
      { controlId: "Art. 11", title: "Sensitive Data Processing", description: "Process sensitive data only under specified circumstances, including consent for specific purposes.", domain: "Legal Bases" },
      { controlId: "Art. 14", title: "Children's Data", description: "Obtain one of the parents' or legal guardians' specific consent when processing children's data.", domain: "Legal Bases" },
      { controlId: "Art. 15", title: "Right to Confirmation and Access", description: "Confirm the existence of processing and access personal data on request.", domain: "Data Subject Rights" },
      { controlId: "Art. 16", title: "Right to Correction", description: "Correct incomplete, inaccurate, or outdated data.", domain: "Data Subject Rights" },
      { controlId: "Art. 17", title: "Right to Anonymization, Blocking, or Deletion", description: "Anonymize, block, or delete unnecessary, excessive, or non-compliant data.", domain: "Data Subject Rights" },
      { controlId: "Art. 18", title: "Right to Portability", description: "Port personal data to another service provider at the request of the data subject.", domain: "Data Subject Rights" },
      { controlId: "Art. 18(VII)", title: "Right to Review Automated Decisions", description: "Review decisions made solely on automated processing that affect the data subject's interests.", domain: "Data Subject Rights" },
      { controlId: "Art. 19", title: "Data Subject Requests", description: "Respond to data subject requests promptly, simply, and free of charge.", domain: "Data Subject Rights" },
      { controlId: "Art. 37", title: "Data Protection Officer", description: "Designate a data protection officer to oversee compliance, communicate with the ANPD, and guide personnel.", domain: "Controller and Processor" },
      { controlId: "Art. 41", title: "Record of Processing Operations", description: "Keep records of processing operations, particularly based on legitimate interest.", domain: "Controller and Processor" },
      { controlId: "Art. 46", title: "Security Measures", description: "Adopt administrative, technical, and organizational security measures protecting personal data.", domain: "Controller and Processor" },
      { controlId: "Art. 48", title: "Incident Notification", description: "Communicate to the ANPD and affected data subjects security incidents that present risk or relevant damage.", domain: "Controller and Processor" },
      { controlId: "Art. 33", title: "International Transfers", description: "Transfer data internationally only where the destination provides an adequate level of protection or under appropriate safeguards.", domain: "International Transfers" },
      { controlId: "Art. 50", title: "Cooperation with the ANPD", description: "Cooperate with the National Data Protection Authority in its oversight activities.", domain: "Supervision" },
      { controlId: "Art. 52", title: "Sanctions", description: "Be subject to sanctions including warnings, fines of up to 2% of turnover, and blocking of processing for violations.", domain: "Supervision" },
    ],
  },

  "pdpa-sg": {
    version: "2021",
    sourceUrl: "https://www.pdpc.gov.sg/overview-of-pdpa/",
    controls: [
      { controlId: "Obligation 1", title: "Consent Obligation", description: "Obtain consent from individuals before collecting, using, or disclosing their personal data.", domain: "Obligations" },
      { controlId: "Obligation 2", title: "Purpose Limitation Obligation", description: "Collect, use, or disclose personal data only for purposes a reasonable person would consider appropriate.", domain: "Obligations" },
      { controlId: "Obligation 3", title: "Notification Obligation", description: "Inform individuals of the purposes of collection, use, or disclosure on or before collection.", domain: "Obligations" },
      { controlId: "Obligation 4", title: "Access and Correction Obligation", description: "Provide individuals access to their personal data and allow correction of inaccurate data.", domain: "Obligations" },
      { controlId: "Obligation 5", title: "Accuracy Obligation", description: "Make reasonable efforts to ensure personal data is accurate and complete.", domain: "Obligations" },
      { controlId: "Obligation 6", title: "Protection Obligation", description: "Protect personal data in your possession from unauthorized access, collection, use, disclosure, or similar risks.", domain: "Obligations" },
      { controlId: "Obligation 7", title: "Retention Limitation Obligation", description: "Cease to retain personal data once no longer needed for business or legal purposes.", domain: "Obligations" },
      { controlId: "Obligation 8", title: "Transfer Limitation Obligation", description: "Transfer personal data to overseas recipients only with comparable protection and appropriate contracts.", domain: "Obligations" },
      { controlId: "Obligation 9", title: "Breach Notification", description: "Notify the PDPC and affected individuals of data breaches that result in significant harm.", domain: "Obligations" },
      { controlId: "Obligation 10", title: "Data Protection Officer", description: "Appoint at least one DPO and make the business contact information publicly available.", domain: "Accountability" },
      { controlId: "Obligation 11", title: "Data Protection Policies and Practices", description: "Develop policies and practices that are necessary to meet data protection obligations.", domain: "Accountability" },
      { controlId: "Obligation 12", title: "Compliance with PDPC Directions", description: "Comply with directions issued by the Personal Data Protection Commission.", domain: "Accountability" },
    ],
  },

  "nist-privacy-framework": {
    version: "1.0",
    sourceUrl: "https://www.nist.gov/privacy-framework",
    controls: [
      { controlId: "ID.IM-P1", title: "Inventory of PII", description: "Maintain a current inventory of systems, products, and services that process PII.", domain: "Identify" },
      { controlId: "ID.RA-P1", title: "Privacy Risk Assessment", description: "Identify privacy risks to individuals arising from data processing and analytics.", domain: "Identify" },
      { controlId: "ID.RA-P2", title: "Data Processing Mapping", description: "Map the processing and flow of data across the data life cycle.", domain: "Identify" },
      { controlId: "ID.RA-P3", title: "Dignity-Type and Tangible Harms", description: "Identify problems to individuals that are dignity-type or tangible in nature.", domain: "Identify" },
      { controlId: "GV.PO-P1", title: "Privacy Governance", description: "Establish a governance structure defining privacy roles, responsibilities, and accountability.", domain: "Govern" },
      { controlId: "GV.PO-P2", title: "Privacy Strategy", description: "Develop a strategy that incorporates the privacy interests of stakeholders.", domain: "Govern" },
      { controlId: "GV.PO-P3", title: "Privacy Policy and Procedures", description: "Establish and maintain policies and procedures for managing privacy risk.", domain: "Govern" },
      { controlId: "GV.RM-P1", title: "Privacy Risk Management Strategy", description: "Establish and communicate the organizational privacy risk management strategy.", domain: "Govern" },
      { controlId: "GV.RM-P2", title: "Privacy Risk Monitoring", description: "Monitor and adjust privacy risk management strategy based on the risk environment.", domain: "Govern" },
      { controlId: "GV.SC-P1", title: "Supply Chain Privacy Risk", description: "Understand and manage privacy risks posed by third parties and supply chains.", domain: "Govern" },
      { controlId: "GV.AT-P1", title: "Privacy Awareness", description: "Provide privacy awareness and training to the workforce.", domain: "Govern" },
      { controlId: "CT.DP-P1", title: "Data Processing Transparency", description: "Communicate data processing purposes and practices to individuals to enable informed decisions.", domain: "Control" },
      { controlId: "CT.DM-P1", title: "Data Minimization", description: "Collect and process only the data necessary to meet objectives and priorities.", domain: "Control" },
      { controlId: "CT.DM-P2", title: "Data Limitation", description: "Reduce the amount of data processed by controlling use, retention, and disposal.", domain: "Control" },
      { controlId: "CT.PO-P1", title: "Permission and Notice", description: "Confirm that processing activities are lawful and provide individuals with relevant notice.", domain: "Control" },
      { controlId: "CT.PO-P2", title: "Consent and Choice", description: "Manage consent and choice where individuals are asked to authorize processing.", domain: "Control" },
      { controlId: "CT.PO-P3", title: "Privacy by Design", description: "Integrate privacy considerations into the design of systems, products, and services.", domain: "Control" },
      { controlId: "CT.PO-P4", title: "Data Protection Impact Assessments", description: "Assess the privacy impact of processing activities and systems before deployment.", domain: "Control" },
      { controlId: "CT.PO-P5", title: "Data Subject Rights", description: "Enable individuals to exercise their rights, including access, correction, and deletion.", domain: "Control" },
      { controlId: "CT.PO-P6", title: "Automated Decision-Making", description: "Provide transparency and human review for automated decisions affecting individuals.", domain: "Control" },
      { controlId: "CM.DC-P1", title: "Data Processing Risk Management", description: "Manage risks to individuals during processing, use, and maintenance of data.", domain: "Communicate" },
      { controlId: "CM.SC-P1", title: "Third-Party Communication", description: "Communicate privacy risks to and from third parties.", domain: "Communicate" },
      { controlId: "CM.PA-P1", title: "Breach Response", description: "Respond to and communicate data breaches and other privacy events.", domain: "Communicate" },
      { controlId: "PR.DS-P1", title: "Data Security", description: "Protect data from unauthorized access, disclosure, and destruction.", domain: "Protect" },
      { controlId: "PR.DS-P2", title: "Data Integrity", description: "Protect data integrity and prevent corruption or unauthorized modification.", domain: "Protect" },
      { controlId: "PR.PO-P1", title: "Data Processing Policies", description: "Establish and implement policies governing processing throughout the data life cycle.", domain: "Protect" },
      { controlId: "PR.PO-P2", title: "Data Retention and Disposal", description: "Retain and dispose of data consistent with stated commitments and requirements.", domain: "Protect" },
    ],
  },

  "eu-ai-act": {
    version: "2024/1689",
    sourceUrl: "https://artificialintelligenceact.eu/",
    controls: [
      { controlId: "Art. 5", title: "Prohibited AI Practices", description: "Prohibit AI practices that deploy subliminal techniques, exploit vulnerabilities, or enable social scoring.", domain: "General Obligations" },
      { controlId: "Art. 9", title: "Risk Management System", description: "Establish, implement, document, and maintain a risk management system for high-risk AI systems.", domain: "High-Risk AI Requirements" },
      { controlId: "Art. 10", title: "Data and Data Governance", description: "Ensure training, validation, and testing datasets are relevant, representative, and free of errors and bias.", domain: "High-Risk AI Requirements" },
      { controlId: "Art. 11", title: "Technical Documentation", description: "Draw up technical documentation demonstrating compliance before placing high-risk AI on the market.", domain: "High-Risk AI Requirements" },
      { controlId: "Art. 12", title: "Record-Keeping", description: "Enable automatic recording of events over the AI system's lifetime to ensure traceability.", domain: "High-Risk AI Requirements" },
      { controlId: "Art. 13", title: "Transparency and Provision of Information to Deployers", description: "Design high-risk AI systems with instructions for use and sufficient transparency for deployers.", domain: "High-Risk AI Requirements" },
      { controlId: "Art. 14", title: "Human Oversight", description: "Design high-risk AI systems to enable effective human oversight, including the ability to intervene and override.", domain: "High-Risk AI Requirements" },
      { controlId: "Art. 15", title: "Accuracy, Robustness, and Cybersecurity", description: "Achieve an appropriate level of accuracy, robustness, and cybersecurity throughout the AI system's lifetime.", domain: "High-Risk AI Requirements" },
      { controlId: "Art. 16", title: "Provider Obligations", description: "Providers implement quality management, maintain documentation, apply corrective actions, and cooperate with authorities.", domain: "Obligations of Providers and Deployers" },
      { controlId: "Art. 20", title: "Non-Compliance and Corrective Action", description: "Take corrective measures and withdraw or recall non-compliant high-risk AI systems.", domain: "Obligations of Providers and Deployers" },
      { controlId: "Art. 26", title: "Deployer Obligations", description: "Deployers use systems per instructions, monitor for risks, and inform providers and authorities of incidents.", domain: "Obligations of Providers and Deployers" },
      { controlId: "Art. 40", title: "General-Purpose AI Model Obligations", description: "General-purpose AI models maintain documentation and provide information to downstream providers.", domain: "General-Purpose AI" },
      { controlId: "Art. 50", title: "Transparency Obligations for AI Systems", description: "Inform individuals when interacting with AI, label deepfakes, and disclose synthetic content.", domain: "Transparency" },
      { controlId: "Art. 55", title: "Foundation Models with Systemic Risk", description: "High-impact foundation models conduct model evaluations, adversarial testing, and incident reporting.", domain: "General-Purpose AI" },
      { controlId: "Art. 62", title: "Conformity Assessment", description: "Undertake conformity assessment procedures before placing high-risk AI systems on the market.", domain: "Governance and Enforcement" },
      { controlId: "Art. 69", title: "Post-Market Monitoring", description: "Establish and maintain a post-market monitoring system for high-risk AI systems.", domain: "Governance and Enforcement" },
      { controlId: "Art. 73", title: "Incident Reporting", description: "Report serious incidents involving high-risk AI systems to the relevant market surveillance authority.", domain: "Governance and Enforcement" },
    ],
  },

  dpdpa: {
    version: "2023",
    sourceUrl: "https://www.meity.gov.in/data-protection-framework",
    controls: [
      { controlId: "S.5", title: "Lawful Processing of Personal Data", description: "Process digital personal data only for lawful purposes, on the basis of consent or a legitimate use.", domain: "Obligations of Data Fiduciary" },
      { controlId: "S.6", title: "Notice and Consent", description: "Give a clear notice of processing and obtain free, specific, informed, unconditional, and unambiguous consent before processing personal data.", domain: "Obligations of Data Fiduciary" },
      { controlId: "S.7", title: "Notice Before Consent", description: "Provide the notice at or before seeking consent, in clear and plain language, in a readily accessible form.", domain: "Obligations of Data Fiduciary" },
      { controlId: "S.8", title: "Consent Managers", description: "Facilitate consent management through an accessible, transparent, and interoperable platform (Consent Manager).", domain: "Obligations of Data Fiduciary" },
      { controlId: "S.9", title: "Processing of Personal Data of Children", description: "Obtain verifiable parental consent before processing a child's personal data and avoid tracking or targeted advertising.", domain: "Obligations of Data Fiduciary" },
      { controlId: "S.10", title: "De-Identification and Retention", description: "De-identify personal data, restrict retention to the purpose, and securely erase data when the purpose is served.", domain: "Obligations of Data Fiduciary" },
      { controlId: "S.11", title: "Purpose Limitation", description: "Process personal data only for the purposes specified in the notice and compatible with those purposes.", domain: "Obligations of Data Fiduciary" },
      { controlId: "S.12", title: "Security Safeguards", description: "Implement reasonable security safeguards and procedures to prevent data breaches or misuse of personal data.", domain: "Obligations of Data Fiduciary" },
      { controlId: "S.13", title: "Data Breach Notification", description: "Notify the Data Protection Board and affected data principals of a personal data breach.", domain: "Obligations of Data Fiduciary" },
      { controlId: "S.16", title: "Grounds for Processing Legitimate Uses", description: "Process personal data without consent only for specified legitimate uses such as state functions, medical emergencies, or employment.", domain: "Legitimate Uses" },
      { controlId: "S.17", title: "Intimate Images and Data Relating to Security", description: "Process intimate images only with consent and protect personal data relating to state security or public order.", domain: "Legitimate Uses" },
      { controlId: "S.18", title: "Transfer of Personal Data", description: "Transfer personal data outside India only subject to exceptions, with intimation of cross-border transfer details.", domain: "Cross-Border Transfer" },
      { controlId: "S.19", title: "Duties of Data Principal", description: "Data principals must not register false complaints, suppress material information, or furnish false particulars.", domain: "Rights and Duties of Data Principal" },
      { controlId: "S.22", title: "Data Protection Officer", description: "Significant data fiduciaries appoint a Data Protection Officer, registered with the Data Protection Board, and a DPO contact base.", domain: "Significant Data Fiduciaries" },
      { controlId: "S.23", title: "Significant Data Fiduciary Obligations", description: "Undertake periodic data protection impact assessments and audits, including algorithms and data processing activities.", domain: "Significant Data Fiduciaries" },
      { controlId: "S.27", title: "Data Protection Impact Assessment", description: "Conduct a data protection impact assessment for processing that poses high risk to the rights of data principals.", domain: "Significant Data Fiduciaries" },
      { controlId: "S.28", title: "Audit of Data Fiduciaries", description: "Undergo an audit of data processing and protection measures at defined intervals.", domain: "Significant Data Fiduciaries" },
      { controlId: "S.29", title: "Records of Processing", description: "Maintain records of all processing operations, purposes, and categories of data processed.", domain: "Obligations of Data Fiduciary" },
      { controlId: "S.30", title: "Data Protection Board", description: "Establish a Data Protection Board of India to enforce the Act, receive complaints, and direct remediation.", domain: "Data Protection Board" },
      { controlId: "S.31", title: "Rights of Data Principal", description: "Ensure the right to access, correction, erasure, and grievance redressal for data principals.", domain: "Rights and Duties of Data Principal" },
      { controlId: "S.32", title: "Right to Grievance Redressal", description: "Address grievances of data principals within a prescribed period and inform them of the outcome.", domain: "Rights and Duties of Data Principal" },
    ],
  },
};
