import type { Catalog } from "./index";
import { nistCsfCatalog } from "./generatedNistCsf";

export const securityCatalogs: Record<string, Catalog> = {
  "nist-csf": nistCsfCatalog,

  "nist-sp-800-53": {
    version: "Rev 5",
    sourceUrl: "https://csrc.nist.gov/pubs/sp/800/53/r5/upd1/final",
    controls: [
      { controlId: "AC-1", title: "Policy and Procedures", description: "Develop, disseminate, and review access control policy and procedures.", domain: "Access Control" },
      { controlId: "AC-2", title: "Account Management", description: "Manage information system accounts, including identification, authorization, and lifecycle.", domain: "Access Control" },
      { controlId: "AC-3", title: "Access Enforcement", description: "Enforce approved authorizations for logical access to information and system resources.", domain: "Access Control" },
      { controlId: "AC-4", title: "Information Flow Enforcement", description: "Enforce authorized information flow control policies between system components.", domain: "Access Control" },
      { controlId: "AC-5", title: "Separation of Duties", description: "Separate duties of individuals to reduce risk of malevolent activity without collusion.", domain: "Access Control" },
      { controlId: "AC-6", title: "Least Privilege", description: "Employ least privilege, allowing only authorized access for users required for job functions.", domain: "Access Control" },
      { controlId: "AC-7", title: "Unsuccessful Logon Attempts", description: "Enforce a limit of consecutive invalid logon attempts and lock the account.", domain: "Access Control" },
      { controlId: "AC-8", title: "System Use Notification", description: "Display system use notification before granting access.", domain: "Access Control" },
      { controlId: "AC-11", title: "Device Lock", description: "Prevent further access by locking sessions after defined inactivity.", domain: "Access Control" },
      { controlId: "AC-12", title: "Session Termination", description: "Automatically terminate user sessions after defined conditions or periods of inactivity.", domain: "Access Control" },
      { controlId: "AC-17", title: "Remote Access", description: "Authorize, monitor, and control remote access to the system.", domain: "Access Control" },
      { controlId: "AC-18", title: "Wireless Access", description: "Authorize, monitor, and control wireless access to the system.", domain: "Access Control" },
      { controlId: "AC-19", title: "Access Control for Mobile Devices", description: "Establish usage restrictions and configuration requirements for mobile devices.", domain: "Access Control" },
      { controlId: "AC-20", title: "Use of External Systems", description: "Establish terms and conditions for use of external information systems.", domain: "Access Control" },
      { controlId: "AC-21", title: "Information Sharing", description: "Facilitate information sharing by enabling authorized users to make sharing decisions.", domain: "Access Control" },
      { controlId: "AC-23", title: "Data Mining Protection", description: "Employ techniques to limit or prevent data mining of sensitive data.", domain: "Access Control" },
      { controlId: "AT-1", title: "Policy and Procedures", description: "Develop, disseminate, and review security awareness and training policy and procedures.", domain: "Awareness and Training" },
      { controlId: "AT-2", title: "Literacy Training and Awareness", description: "Provide security and privacy literacy training that is role-based and occurs at defined intervals.", domain: "Awareness and Training" },
      { controlId: "AT-3", title: "Role-Based Training", description: "Provide role-based security and privacy training to personnel before granting access and periodically thereafter.", domain: "Awareness and Training" },
      { controlId: "AT-4", title: "Training Records", description: "Document and monitor individual training activities.", domain: "Awareness and Training" },
      { controlId: "AU-1", title: "Policy and Procedures", description: "Develop, disseminate, and review audit and accountability policy and procedures.", domain: "Audit and Accountability" },
      { controlId: "AU-2", title: "Event Logging", description: "Identify the system events that are logged and the events that require logging.", domain: "Audit and Accountability" },
      { controlId: "AU-3", title: "Content of Audit Records", description: "Ensure audit records contain information needed to determine the source and outcome of events.", domain: "Audit and Accountability" },
      { controlId: "AU-4", title: "Audit Log Storage Capacity", description: "Allocate audit log storage capacity to accommodate logging requirements.", domain: "Audit and Accountability" },
      { controlId: "AU-6", title: "Audit Record Review, Analysis, and Reporting", description: "Review and analyze audit records for indications of inappropriate or unusual activity.", domain: "Audit and Accountability" },
      { controlId: "AU-7", title: "Audit Record Reduction and Report Generation", description: "Provide and support tools to reduce and generate reports from audit records.", domain: "Audit and Accountability" },
      { controlId: "AU-8", title: "Time Stamps", description: "Use internal system clocks to generate time stamps for audit records.", domain: "Audit and Accountability" },
      { controlId: "AU-9", title: "Protection of Audit Information", description: "Protect audit information and audit tools from unauthorized access, modification, and deletion.", domain: "Audit and Accountability" },
      { controlId: "AU-11", title: "Audit Record Retention", description: "Retain audit records for a time period consistent with records retention policy.", domain: "Audit and Accountability" },
      { controlId: "AU-12", title: "Audit Record Generation", description: "Provide audit record generation capability for defined events across system components.", domain: "Audit and Accountability" },
      { controlId: "CA-1", title: "Policy and Procedures", description: "Develop, disseminate, and review assessment, authorization, and monitoring policy.", domain: "Assessment, Authorization, and Monitoring" },
      { controlId: "CA-2", title: "Control Assessments", description: "Assess the effectiveness of controls in achieving stated objectives at defined intervals.", domain: "Assessment, Authorization, and Monitoring" },
      { controlId: "CA-5", title: "Plan of Action and Milestones", description: "Develop and maintain a plan of action and milestones for remediating weaknesses.", domain: "Assessment, Authorization, and Monitoring" },
      { controlId: "CA-7", title: "Continuous Monitoring", description: "Develop and implement a continuous monitoring strategy for the system and its controls.", domain: "Assessment, Authorization, and Monitoring" },
      { controlId: "CA-9", title: "Internal System Connections", description: "Authorize internal connections of system components or discrete systems before connection.", domain: "Assessment, Authorization, and Monitoring" },
      { controlId: "CM-1", title: "Policy and Procedures", description: "Develop, disseminate, and review configuration management policy and procedures.", domain: "Configuration Management" },
      { controlId: "CM-2", title: "Baseline Configuration", description: "Develop and maintain a baseline configuration of the system and components.", domain: "Configuration Management" },
      { controlId: "CM-3", title: "Configuration Change Control", description: "Review, approve, and track changes to the system with configuration change control.", domain: "Configuration Management" },
      { controlId: "CM-5", title: "Access Restrictions for Change", description: "Define, document, approve, and enforce logical and physical access restrictions for changes.", domain: "Configuration Management" },
      { controlId: "CM-6", title: "Configuration Settings", description: "Establish and enforce security configuration settings for products employed.", domain: "Configuration Management" },
      { controlId: "CM-7", title: "Least Functionality", description: "Restrict functionality to the minimum required for system operation.", domain: "Configuration Management" },
      { controlId: "CM-8", title: "System Component Inventory", description: "Develop, document, and maintain an inventory of system components.", domain: "Configuration Management" },
      { controlId: "CM-9", title: "Configuration Management Plan", description: "Develop and implement a configuration management plan for the system.", domain: "Configuration Management" },
      { controlId: "CM-10", title: "Software Usage Restrictions", description: "Restrict the use of software to that which is supported and licensed.", domain: "Configuration Management" },
      { controlId: "CM-11", title: "User-Installed Software", description: "Establish policies governing the installation of software by users.", domain: "Configuration Management" },
      { controlId: "CP-1", title: "Policy and Procedures", description: "Develop, disseminate, and review contingency planning policy and procedures.", domain: "Contingency Planning" },
      { controlId: "CP-2", title: "Contingency Plan", description: "Develop and maintain a contingency plan for the system to enable recovery after disruption.", domain: "Contingency Planning" },
      { controlId: "CP-3", title: "Contingency Training", description: "Provide contingency training to personnel with contingency plan responsibilities.", domain: "Contingency Planning" },
      { controlId: "CP-4", title: "Contingency Plan Testing", description: "Test the contingency plan to determine its effectiveness and readiness.", domain: "Contingency Planning" },
      { controlId: "CP-6", title: "Alternate Storage Site", description: "Establish an alternate storage site to store duplicate copies of information.", domain: "Contingency Planning" },
      { controlId: "CP-7", title: "Alternate Processing Site", description: "Establish an alternate processing site and resume operations within defined time periods.", domain: "Contingency Planning" },
      { controlId: "CP-8", title: "Telecommunications Services", description: "Establish alternate telecommunications services for critical system operations.", domain: "Contingency Planning" },
      { controlId: "CP-9", title: "System Backup", description: "Conduct backups of user-level and system-level information at defined frequencies.", domain: "Contingency Planning" },
      { controlId: "CP-10", title: "System Recovery and Reconstitution", description: "Recover and reconstitute the system within recovery time objectives.", domain: "Contingency Planning" },
      { controlId: "IA-1", title: "Policy and Procedures", description: "Develop, disseminate, and review identification and authentication policy and procedures.", domain: "Identification and Authentication" },
      { controlId: "IA-2", title: "Identification and Authentication for Organizational Users", description: "Uniquely identify and authenticate organizational users and processes.", domain: "Identification and Authentication" },
      { controlId: "IA-3", title: "Device Identification and Authentication", description: "Uniquely identify and authenticate devices before establishing a connection.", domain: "Identification and Authentication" },
      { controlId: "IA-4", title: "Identifier Management", description: "Manage system identifiers for users and devices.", domain: "Identification and Authentication" },
      { controlId: "IA-5", title: "Authenticator Management", description: "Manage system authenticators, including initial distribution and reset.", domain: "Identification and Authentication" },
      { controlId: "IA-6", title: "Authenticator Feedback", description: "Obscure feedback of authentication information during the authentication process.", domain: "Identification and Authentication" },
      { controlId: "IA-7", title: "Cryptographic Module Authentication", description: "Implement mechanisms for authentication to cryptographic modules meeting requirements.", domain: "Identification and Authentication" },
      { controlId: "IA-8", title: "Identification and Authentication for Non-Organizational Users", description: "Uniquely identify and authenticate non-organizational users.", domain: "Identification and Authentication" },
      { controlId: "IR-1", title: "Policy and Procedures", description: "Develop, disseminate, and review incident response policy and procedures.", domain: "Incident Response" },
      { controlId: "IR-2", title: "Incident Response Training", description: "Provide incident response training consistent with assigned roles and responsibilities.", domain: "Incident Response" },
      { controlId: "IR-3", title: "Incident Response Testing", description: "Test incident response capabilities at defined intervals.", domain: "Incident Response" },
      { controlId: "IR-4", title: "Incident Handling", description: "Implement incident handling capability for preparation, detection, analysis, containment, and recovery.", domain: "Incident Response" },
      { controlId: "IR-5", title: "Incident Monitoring", description: "Track and document system security incidents.", domain: "Incident Response" },
      { controlId: "IR-6", title: "Incident Reporting", description: "Require personnel to report suspected incidents, and report incidents to authorities within defined time periods.", domain: "Incident Response" },
      { controlId: "IR-7", title: "Incident Response Assistance", description: "Provide an incident response support resource offering advice and assistance.", domain: "Incident Response" },
      { controlId: "IR-8", title: "Incident Response Plan", description: "Establish and maintain a formal incident response plan.", domain: "Incident Response" },
      { controlId: "IR-9", title: "Information Spillage Response", description: "Respond to information spills in accordance with the incident response plan.", domain: "Incident Response" },
      { controlId: "MA-2", title: "Controlled Maintenance", description: "Schedule and document maintenance, and approve all maintenance activities.", domain: "Maintenance" },
      { controlId: "MA-3", title: "Maintenance Tools", description: "Approve, control, and monitor maintenance tools used on the system.", domain: "Maintenance" },
      { controlId: "MA-4", title: "Nonlocal Maintenance", description: "Approve and monitor nonlocal maintenance and diagnostic activities.", domain: "Maintenance" },
      { controlId: "MA-5", title: "Maintenance Personnel", description: "Establish a process for maintenance personnel authorization and ensure escorts where required.", domain: "Maintenance" },
      { controlId: "MP-2", title: "Media Access", description: "Restrict access to digital and non-digital media to authorized personnel.", domain: "Media Protection" },
      { controlId: "MP-3", title: "Media Marking", description: "Mark system media indicating the distribution limitations and handling caveats.", domain: "Media Protection" },
      { controlId: "MP-4", title: "Media Storage", description: "Physically control and securely store system media within controlled areas.", domain: "Media Protection" },
      { controlId: "MP-5", title: "Media Transport", description: "Protect and control system media during transport outside controlled areas.", domain: "Media Protection" },
      { controlId: "MP-6", title: "Media Sanitization", description: "Sanitize system media prior to disposal, release, or reuse.", domain: "Media Protection" },
      { controlId: "PE-1", title: "Policy and Procedures", description: "Develop, disseminate, and review physical and environmental protection policy.", domain: "Physical and Environmental Protection" },
      { controlId: "PE-2", title: "Physical Access Authorizations", description: "Develop and approve a list of individuals authorized to enter the facility where the system resides.", domain: "Physical and Environmental Protection" },
      { controlId: "PE-3", title: "Physical Access Control", description: "Enforce physical access authorizations and control entry to facilities and areas.", domain: "Physical and Environmental Protection" },
      { controlId: "PE-6", title: "Monitoring Physical Access", description: "Monitor physical access to the facility and system areas to detect unauthorized activity.", domain: "Physical and Environmental Protection" },
      { controlId: "PE-8", title: "Visitor Access Records", description: "Maintain visitor access records for the facility where the system resides.", domain: "Physical and Environmental Protection" },
      { controlId: "PE-9", title: "Power Equipment and Cabling", description: "Protect power equipment and power and cooling cabling for the system.", domain: "Physical and Environmental Protection" },
      { controlId: "PE-11", title: "Emergency Power", description: "Provide short-term uninterruptible power to facilitate an orderly shutdown or transition.", domain: "Physical and Environmental Protection" },
      { controlId: "PE-13", title: "Fire Protection", description: "Employ and maintain fire suppression and detection devices and systems.", domain: "Physical and Environmental Protection" },
      { controlId: "PE-14", title: "Environmental Controls", description: "Maintain temperature and humidity levels within acceptable limits.", domain: "Physical and Environmental Protection" },
      { controlId: "PE-15", title: "Water Damage Protection", description: "Protect the system from damage resulting from water leakage.", domain: "Physical and Environmental Protection" },
      { controlId: "PE-16", title: "Delivery and Removal", description: "Authorize, monitor, and control system-related items entering and exiting the facility.", domain: "Physical and Environmental Protection" },
      { controlId: "PL-2", title: "System Security and Privacy Plans", description: "Develop and maintain a system security and privacy plan describing the system and its controls.", domain: "Planning" },
      { controlId: "PL-4", title: "Rules of Behavior", description: "Establish and make available rules of behavior for system use.", domain: "Planning" },
      { controlId: "PL-8", title: "Security and Privacy Architectures", description: "Develop and document architectures that reflect and support the security and privacy requirements.", domain: "Planning" },
      { controlId: "PM-1", title: "Information Security Program Plan", description: "Develop and implement an information security program plan.", domain: "Program Management" },
      { controlId: "PM-2", title: "Information Security Program Leadership Role", description: "Appoint a senior agency information security officer with program authority.", domain: "Program Management" },
      { controlId: "PM-3", title: "Information Security and Privacy Resources", description: "Allocate resources dedicated to establishing and sustaining the security and privacy programs.", domain: "Program Management" },
      { controlId: "PM-4", title: "Plan of Action and Milestones Process", description: "Implement a process for managing plans of action and milestones.", domain: "Program Management" },
      { controlId: "PM-8", title: "Critical Infrastructure Plan", description: "Address information security in the protection of critical infrastructure assets.", domain: "Program Management" },
      { controlId: "PM-9", title: "Risk Management Strategy", description: "Establish and maintain a comprehensive risk management strategy.", domain: "Program Management" },
      { controlId: "PM-10", title: "Security Authorization Process", description: "Employ a security authorization process to manage organizational risk.", domain: "Program Management" },
      { controlId: "PM-11", title: "Mission and Business Process Definition", description: "Define mission and business processes with security and privacy considerations.", domain: "Program Management" },
      { controlId: "PM-13", title: "Security and Privacy Workforce", description: "Establish and maintain a workforce with security and privacy skills.", domain: "Program Management" },
      { controlId: "PM-15", title: "Security and Privacy Groups and Associations", description: "Establish and institutionalize contact with selected groups and associations.", domain: "Program Management" },
      { controlId: "PM-16", title: "Threat Awareness Program", description: "Establish a threat awareness program and use threat information to inform decisions.", domain: "Program Management" },
      { controlId: "PS-1", title: "Policy and Procedures", description: "Develop, disseminate, and review personnel security policy and procedures.", domain: "Personnel Security" },
      { controlId: "PS-2", title: "Position Risk Designation", description: "Assign a risk designation to all organizational positions.", domain: "Personnel Security" },
      { controlId: "PS-3", title: "Personnel Screening", description: "Screen individuals prior to authorizing access to the system.", domain: "Personnel Security" },
      { controlId: "PS-4", title: "Personnel Termination", description: "Upon termination, revoke access and promptly disable authenticators and accounts.", domain: "Personnel Security" },
      { controlId: "PS-5", title: "Personnel Transfer", description: "Review and update logical and physical access authorizations when personnel transfer.", domain: "Personnel Security" },
      { controlId: "PS-6", title: "Access Agreements", description: "Establish and enforce access agreements for individuals accessing the system.", domain: "Personnel Security" },
      { controlId: "PS-7", title: "External Personnel Security", description: "Establish personnel security requirements for external personnel.", domain: "Personnel Security" },
      { controlId: "RA-1", title: "Policy and Procedures", description: "Develop, disseminate, and review risk assessment policy and procedures.", domain: "Risk Assessment" },
      { controlId: "RA-2", title: "Security Categorization", description: "Categorize the system and information according to the criticality and sensitivity of the data.", domain: "Risk Assessment" },
      { controlId: "RA-3", title: "Risk Assessment", description: "Conduct risk assessments to identify and analyze risk to operations and assets.", domain: "Risk Assessment" },
      { controlId: "RA-5", title: "Vulnerability Monitoring and Scanning", description: "Scan for vulnerabilities and remediate deficiencies on a defined schedule.", domain: "Risk Assessment" },
      { controlId: "RA-7", title: "Vulnerability Remediation", description: "Remediate system vulnerabilities in accordance with risk assessments.", domain: "Risk Assessment" },
      { controlId: "SA-3", title: "System Development Life Cycle", description: "Manage the system using a system development life cycle that includes security and privacy.", domain: "System and Services Acquisition" },
      { controlId: "SA-4", title: "Acquisition Process", description: "Include security and privacy requirements in system acquisition contracts.", domain: "System and Services Acquisition" },
      { controlId: "SA-8", title: "Security and Privacy Engineering Principles", description: "Apply system security and privacy engineering principles during design and development.", domain: "System and Services Acquisition" },
      { controlId: "SA-9", title: "External System Services", description: "Employ external system services consistent with organizational security requirements.", domain: "System and Services Acquisition" },
      { controlId: "SA-10", title: "Developer Configuration Management", description: "Require developers to perform configuration management during system development.", domain: "System and Services Acquisition" },
      { controlId: "SA-11", title: "Developer Testing and Evaluation", description: "Require developers to perform security testing of components and services.", domain: "System and Services Acquisition" },
      { controlId: "SA-15", title: "Development Process, Standards, and Tools", description: "Require developers to use approved development processes, standards, and tools.", domain: "System and Services Acquisition" },
      { controlId: "SA-21", title: "Developer Screening", description: "Require developers to be screened consistent with organizational personnel screening policy.", domain: "System and Services Acquisition" },
      { controlId: "SC-1", title: "Policy and Procedures", description: "Develop, disseminate, and review system and communications protection policy.", domain: "System and Communications Protection" },
      { controlId: "SC-5", title: "Denial-of-Service Protection", description: "Protect against and limit the effects of denial-of-service events.", domain: "System and Communications Protection" },
      { controlId: "SC-7", title: "Boundary Protection", description: "Monitor and control communications at the external boundary and key internal boundaries.", domain: "System and Communications Protection" },
      { controlId: "SC-8", title: "Transmission Confidentiality and Integrity", description: "Protect the confidentiality and integrity of transmitted information.", domain: "System and Communications Protection" },
      { controlId: "SC-12", title: "Cryptographic Key Establishment and Management", description: "Establish and manage cryptographic keys for required cryptography.", domain: "System and Communications Protection" },
      { controlId: "SC-13", title: "Cryptographic Protection", description: "Implement cryptographic mechanisms in accordance with applicable standards.", domain: "System and Communications Protection" },
      { controlId: "SC-15", title: "Collaborative Computing Devices", description: "Prohibit or restrict use of collaborative computing devices with exception mechanisms.", domain: "System and Communications Protection" },
      { controlId: "SC-20", title: "Secure Name/Address Resolution Service", description: "Provide secure name and address resolution services.", domain: "System and Communications Protection" },
      { controlId: "SC-21", title: "Secure Name/Address Resolution Service (Recursive or Caching Resolver)", description: "Implement recursive or caching resolvers providing additional data origin and integrity artifacts.", domain: "System and Communications Protection" },
      { controlId: "SC-28", title: "Protection of Information at Rest", description: "Protect the confidentiality and integrity of information at rest.", domain: "System and Communications Protection" },
      { controlId: "SC-32", title: "System Partitioning", description: "Partition the system into components residing in separate physical or logical domains.", domain: "System and Communications Protection" },
      { controlId: "SC-39", title: "Process Isolation", description: "Maintain a trusted execution environment for each executing process.", domain: "System and Communications Protection" },
      { controlId: "SI-1", title: "Policy and Procedures", description: "Develop, disseminate, and review system and information integrity policy and procedures.", domain: "System and Information Integrity" },
      { controlId: "SI-2", title: "Flaw Remediation", description: "Identify, report, and correct system flaws in a timely manner.", domain: "System and Information Integrity" },
      { controlId: "SI-3", title: "Malicious Code Protection", description: "Employ malicious code protection mechanisms at key locations and update signatures.", domain: "System and Information Integrity" },
      { controlId: "SI-4", title: "System Monitoring", description: "Monitor the system to detect attacks and unauthorized activity.", domain: "System and Information Integrity" },
      { controlId: "SI-5", title: "Security Alerts, Advisories, and Directives", description: "Receive and generate system security alerts, advisories, and directives.", domain: "System and Information Integrity" },
      { controlId: "SI-7", title: "Software, Firmware, and Information Integrity", description: "Employ integrity verification tools to detect unauthorized changes.", domain: "System and Information Integrity" },
      { controlId: "SI-10", title: "Information Input Validation", description: "Check the validity of information inputs.", domain: "System and Information Integrity" },
      { controlId: "SI-11", title: "Error Handling", description: "Generate error messages that do not reveal sensitive information.", domain: "System and Information Integrity" },
      { controlId: "SI-12", title: "Information Handling and Retention", description: "Handle and retain information within the system in accordance with applicable policy.", domain: "System and Information Integrity" },
      { controlId: "SI-16", title: "Memory Protection", description: "Implement safeguards to protect system memory from unauthorized code execution.", domain: "System and Information Integrity" },
      { controlId: "SR-1", title: "Policy and Procedures", description: "Develop, disseminate, and review supply chain risk management policy and procedures.", domain: "Supply Chain Risk Management" },
      { controlId: "SR-2", title: "Supply Chain Risk Management Plan", description: "Develop and implement a plan for managing supply chain risks.", domain: "Supply Chain Risk Management" },
      { controlId: "SR-3", title: "Supply Chain Controls and Processes", description: "Establish processes for identifying, addressing, and tracking supply chain risks.", domain: "Supply Chain Risk Management" },
      { controlId: "SR-4", title: "Provenance", description: "Document the source of components to establish provenance.", domain: "Supply Chain Risk Management" },
      { controlId: "SR-5", title: "Acquisition Strategies, Tools, and Methods", description: "Employ acquisition strategies, tools, and methods to protect against supply chain threats.", domain: "Supply Chain Risk Management" },
      { controlId: "SR-8", title: "Notification Agreements", description: "Establish agreements with suppliers requiring notification of compromises.", domain: "Supply Chain Risk Management" },
      { controlId: "SR-10", title: "Inspection of Systems or Components", description: "Inspect systems or system components for tampering and corruption at defined points.", domain: "Supply Chain Risk Management" },
      { controlId: "SR-11", title: "Component Authenticity", description: "Develop and implement anti-counterfeit policies and mechanisms.", domain: "Supply Chain Risk Management" },
    ],
  },

  "cis-controls": {
    version: "v8",
    sourceUrl: "https://www.cisecurity.org/controls/v8",
    controls: [
      { controlId: "CIS-01", title: "Inventory and Control of Enterprise Assets", description: "Actively manage all enterprise assets including hardware and software to know what to protect.", domain: "Basic Controls" },
      { controlId: "CIS-02", title: "Inventory and Control of Software Assets", description: "Actively manage all software on the network to ensure only authorized software is installed.", domain: "Basic Controls" },
      { controlId: "CIS-03", title: "Data Protection", description: "Develop processes and technical controls to identify, classify, securely handle, retain, and dispose of data.", domain: "Basic Controls" },
      { controlId: "CIS-04", title: "Secure Configuration of Enterprise Assets and Software", description: "Establish and maintain the secure configuration of enterprise assets and software.", domain: "Basic Controls" },
      { controlId: "CIS-05", title: "Account Management", description: "Use processes and tools to assign and manage authorization to credentials for user accounts.", domain: "Basic Controls" },
      { controlId: "CIS-06", title: "Access Control Management", description: "Use processes and tools to create, assign, manage, and revoke access to assets.", domain: "Basic Controls" },
      { controlId: "CIS-07", title: "Continuous Vulnerability Management", description: "Develop a plan to continuously assess and track vulnerabilities and remediate them.", domain: "Basic Controls" },
      { controlId: "CIS-08", title: "Audit Log Management", description: "Collect, alert, review, and retain audit logs of events to detect and understand attacks.", domain: "Basic Controls" },
      { controlId: "CIS-09", title: "Email and Web Browser Protections", description: "Improve protections and detections of email and web vectors.", domain: "Basic Controls" },
      { controlId: "CIS-10", title: "Malware Defenses", description: "Prevent or control the installation, spread, and execution of malicious applications.", domain: "Basic Controls" },
      { controlId: "CIS-11", title: "Data Recovery", description: "Establish and maintain data recovery practices sufficient to restore assets to a known state.", domain: "Basic Controls" },
      { controlId: "CIS-12", title: "Network Infrastructure Management", description: "Establish, implement, and actively manage network devices to prevent attackers from exploiting network connections.", domain: "Basic Controls" },
      { controlId: "CIS-13", title: "Network Monitoring and Defense", description: "Operate processes and tools to establish and maintain comprehensive network monitoring and defense.", domain: "Basic Controls" },
      { controlId: "CIS-14", title: "Security Awareness and Skills Training", description: "Establish and maintain a security awareness program to influence secure behavior.", domain: "Basic Controls" },
      { controlId: "CIS-15", title: "Service Provider Management", description: "Evaluate the security of service providers and ensure contractual requirements reduce risk.", domain: "Basic Controls" },
      { controlId: "CIS-16", title: "Application Software Security", description: "Manage the security life cycle of in-house developed and acquired application software.", domain: "Basic Controls" },
      { controlId: "CIS-17", title: "Incident Response Management", description: "Establish a program to develop and maintain an incident response capability.", domain: "Basic Controls" },
      { controlId: "CIS-18", title: "Penetration Testing", description: "Test the effectiveness and resiliency of enterprise assets through identifying and exploiting weaknesses.", domain: "Basic Controls" },
    ],
  },

  cmmc: {
    version: "2.0",
    sourceUrl: "https://dodcio.defense.gov/CMMC/",
    controls: [
      { controlId: "3.1.1", title: "Limit System Access to Authorized Users", description: "Limit information system access to authorized users, processes acting on behalf of users, or devices.", domain: "Access Control" },
      { controlId: "3.1.2", title: "Limit System Access to Authorized Transactions", description: "Limit information system access to the types of transactions and functions that authorized users are permitted to execute.", domain: "Access Control" },
      { controlId: "3.1.3", title: "Control CUI Flow", description: "Control the flow of CUI in accordance with approved authorizations.", domain: "Access Control" },
      { controlId: "3.1.4", title: "Separate Duties of Individuals", description: "Separate the duties of individuals to reduce the risk of malevolent activity without collusion.", domain: "Access Control" },
      { controlId: "3.1.5", title: "Employ Least Privilege", description: "Employ the principle of least privilege, including for specific security functions and privileged accounts.", domain: "Access Control" },
      { controlId: "3.1.6", title: "Use Non-Privileged Accounts", description: "Use non-privileged accounts or roles when accessing nonsecurity functions.", domain: "Access Control" },
      { controlId: "3.1.7", title: "Prevent Non-Privileged Users from Executing Privileged Functions", description: "Prevent non-privileged users from executing privileged functions and capture such executions for review.", domain: "Access Control" },
      { controlId: "3.1.8", title: "Limit Unsuccessful Logon Attempts", description: "Limit unsuccessful logon attempts and enforce account lockout.", domain: "Access Control" },
      { controlId: "3.1.12", title: "Monitor and Control Remote Access", description: "Monitor and control remote access sessions and employ cryptographic mechanisms to protect remote sessions.", domain: "Access Control" },
      { controlId: "3.1.16", title: "Control Connection of Mobile Devices", description: "Establish usage restrictions and configuration requirements for mobile devices.", domain: "Access Control" },
      { controlId: "3.1.20", title: "Verify and Control External Connections", description: "Verify and control, as applicable, external connections to the information system.", domain: "Access Control" },
      { controlId: "3.1.22", title: "Control Publicly Accessible Content", description: "Control information posted or processed on publicly accessible systems.", domain: "Access Control" },
      { controlId: "3.2.1", title: "Establish and Maintain Secure Configurations", description: "Establish and maintain baseline configurations and inventories for organizational systems.", domain: "Awareness and Training" },
      { controlId: "3.3.1", title: "Create and Retain Audit Logs", description: "Create and retain system audit logs and records to enable monitoring, analysis, investigation, and reporting.", domain: "Audit and Accountability" },
      { controlId: "3.3.2", title: "Ensure Audit Actions", description: "Ensure that the actions of individual users can be uniquely traced.", domain: "Audit and Accountability" },
      { controlId: "3.3.4", title: "Alert on Audit Failures", description: "Alert in the event of an audit logging process failure.", domain: "Audit and Accountability" },
      { controlId: "3.3.8", title: "Protect Audit Information", description: "Protect audit information and audit tools from unauthorized access, modification, and deletion.", domain: "Audit and Accountability" },
      { controlId: "3.4.1", title: "Establish and Maintain Baseline Configurations", description: "Establish and maintain baseline configurations and inventories of organizational systems.", domain: "Configuration Management" },
      { controlId: "3.4.2", title: "Establish and Enforce Security Configuration Settings", description: "Establish and enforce security configuration settings for products used in organizational systems.", domain: "Configuration Management" },
      { controlId: "3.4.3", title: "Track and Review System Changes", description: "Track, review, approve or disapprove, and log changes to organizational systems.", domain: "Configuration Management" },
      { controlId: "3.5.1", title: "Identify and Authenticate Users", description: "Identify and authenticate organizational users and processes acting on behalf of users.", domain: "Identification and Authentication" },
      { controlId: "3.5.3", title: "Use Multifactor Authentication", description: "Use multifactor authentication for local and network access to privileged and non-privileged accounts.", domain: "Identification and Authentication" },
      { controlId: "3.6.1", title: "Establish an Incident Response Capability", description: "Establish an operational incident-handling capability and provide incident handling training.", domain: "Incident Response" },
      { controlId: "3.6.2", title: "Track and Document Incidents", description: "Track and document information system security incidents.", domain: "Incident Response" },
      { controlId: "3.6.3", title: "Test Incident Response", description: "Test the organizational incident response capability.", domain: "Incident Response" },
      { controlId: "3.7.1", title: "Maintain Maintenance Records", description: "Maintain maintenance records and control maintenance tools and media.", domain: "Maintenance" },
      { controlId: "3.8.1", title: "Protect and Sanitize Media", description: "Protect and control media containing CUI, and sanitize media before disposal or reuse.", domain: "Media Protection" },
      { controlId: "3.8.3", title: "Control Media Use", description: "Control the use of removable media on systems.", domain: "Media Protection" },
      { controlId: "3.9.1", title: "Control Physical Access", description: "Limit physical access to organizational systems and facilities to authorized individuals.", domain: "Physical Protection" },
      { controlId: "3.9.2", title: "Protect Power and Cooling", description: "Protect and monitor the physical power and cooling for organizational systems.", domain: "Physical Protection" },
      { controlId: "3.10.1", title: "Screen Personnel", description: "Screen individuals prior to authorizing access to systems containing CUI.", domain: "Personnel Security" },
      { controlId: "3.10.2", title: "Terminate Access", description: "Terminate access to systems containing CUI when individuals no longer require access.", domain: "Personnel Security" },
      { controlId: "3.11.1", title: "Identify and Document Vulnerabilities", description: "Periodically assess the risk to organizational operations from vulnerabilities.", domain: "Risk Assessment" },
      { controlId: "3.11.2", title: "Remediate Vulnerabilities", description: "Remediate vulnerabilities in accordance with risk assessments.", domain: "Risk Assessment" },
      { controlId: "3.12.1", title: "Control the Use of External Systems", description: "Establish usage restrictions for external systems and protect CUI on external systems.", domain: "System and Services Acquisition" },
      { controlId: "3.13.1", title: "Monitor and Control Communications", description: "Monitor, control, and protect organizational communications at the external and internal boundaries.", domain: "System and Communications Protection" },
      { controlId: "3.13.2", title: "Employ Architectural Designs", description: "Employ architectural designs and techniques that facilitate security.", domain: "System and Communications Protection" },
      { controlId: "3.13.4", title: "Separate Networks", description: "Separate user functionality from system management functionality.", domain: "System and Communications Protection" },
      { controlId: "3.13.8", title: "Implement Cryptographic Mechanisms", description: "Implement cryptographic mechanisms to prevent unauthorized disclosure of CUI during transmission.", domain: "System and Communications Protection" },
      { controlId: "3.13.11", title: "Protect CUI at Rest", description: "Employ mechanisms to prevent unauthorized disclosure of CUI at rest.", domain: "System and Communications Protection" },
      { controlId: "3.13.16", title: "Protect the Confidentiality of CUI", description: "Protect the confidentiality of CUI at rest and in transit using approved methods.", domain: "System and Communications Protection" },
      { controlId: "3.14.1", title: "Identify and Report Flaws", description: "Identify, report, and correct information system flaws in a timely manner.", domain: "System and Information Integrity" },
      { controlId: "3.14.2", title: "Provide Protection from Malicious Code", description: "Provide protection from malicious code at appropriate locations within organizational systems.", domain: "System and Information Integrity" },
      { controlId: "3.14.3", title: "Monitor System Security Alerts", description: "Monitor system security alerts and advisories and act on them.", domain: "System and Information Integrity" },
      { controlId: "3.14.6", title: "Monitor System for Attacks", description: "Monitor organizational systems for attacks and unauthorized activity.", domain: "System and Information Integrity" },
    ],
  },

  "cyber-essentials": {
    version: "3.2",
    sourceUrl: "https://www.ncsc.gov.uk/cyberessentials/overview",
    controls: [
      { controlId: "CE-1", title: "Boundary Firewalls and Internet Gateways", description: "Secure the organization's boundary with a properly configured firewall and internet gateway.", domain: "Technical Controls" },
      { controlId: "CE-2", title: "Secure Configuration", description: "Configure devices and software securely, removing default passwords and unused accounts.", domain: "Technical Controls" },
      { controlId: "CE-3", title: "User Access Control", description: "Limit user accounts and privileges to only what is required, using separate admin accounts.", domain: "Technical Controls" },
      { controlId: "CE-4", title: "Malware Protection", description: "Protect all devices against malware and keep definitions up to date.", domain: "Technical Controls" },
      { controlId: "CE-5", title: "Security Update Management", description: "Apply security updates and patches to all devices and software promptly.", domain: "Technical Controls" },
    ],
  },

  "soc-2": {
    version: "2022",
    sourceUrl: "https://www.aicpa-cima.com/topic/audit-assurance/audit-and-assurance-greater-than-soc-2",
    controls: [
      { controlId: "CC1.1", title: "Control Environment: Integrity and Ethical Values", description: "Demonstrate a commitment to integrity and ethical values.", domain: "Control Environment" },
      { controlId: "CC1.2", title: "Control Environment: Board Oversight", description: "The board of directors oversees the design and operation of internal control.", domain: "Control Environment" },
      { controlId: "CC1.3", title: "Control Environment: Organizational Structure", description: "Establish reporting lines and appropriate responsibilities to achieve objectives.", domain: "Control Environment" },
      { controlId: "CC1.4", title: "Control Environment: Competence", description: "Demonstrate a commitment to attract, develop, and retain competent individuals.", domain: "Control Environment" },
      { controlId: "CC1.5", title: "Control Environment: Accountability", description: "Hold individuals accountable for their internal control responsibilities.", domain: "Control Environment" },
      { controlId: "CC2.1", title: "Communication: Information to Support Objectives", description: "Obtain or generate and use relevant, quality information to support internal control.", domain: "Communication and Information" },
      { controlId: "CC2.2", title: "Communication: Internal Communication", description: "Communicate internally the information necessary to support the functioning of internal control.", domain: "Communication and Information" },
      { controlId: "CC2.3", title: "Communication: External Communication", description: "Communicate externally information about the functioning of internal control.", domain: "Communication and Information" },
      { controlId: "CC3.1", title: "Risk Assessment: Objectives", description: "Specify objectives with sufficient clarity to enable the identification and assessment of risks.", domain: "Risk Assessment" },
      { controlId: "CC3.2", title: "Risk Assessment: Risk Identification and Analysis", description: "Identify and analyze risks to achieve objectives across the entity and its systems.", domain: "Risk Assessment" },
      { controlId: "CC3.3", title: "Risk Assessment: Fraud", description: "Consider the potential for fraud when assessing risks.", domain: "Risk Assessment" },
      { controlId: "CC3.4", title: "Risk Assessment: Change", description: "Identify, assess, and manage changes that could significantly affect internal control.", domain: "Risk Assessment" },
      { controlId: "CC4.1", title: "Monitoring Activities: Ongoing Evaluations", description: "Select, develop, and perform ongoing evaluations of internal control.", domain: "Monitoring Activities" },
      { controlId: "CC4.2", title: "Monitoring Activities: Remediation", description: "Evaluate and communicate internal control deficiencies in a timely manner.", domain: "Monitoring Activities" },
      { controlId: "CC5.1", title: "Control Activities: Selection and Development", description: "Select and develop control activities that contribute to the mitigation of risks.", domain: "Control Activities" },
      { controlId: "CC5.2", title: "Control Activities: Technology", description: "Select and develop general control activities over technology.", domain: "Control Activities" },
      { controlId: "CC5.3", title: "Control Activities: Deployment", description: "Deploy control activities through policies that establish expectations.", domain: "Control Activities" },
      { controlId: "CC6.1", title: "Logical and Physical Access", description: "Restrict logical and physical access to assets to meet the security objective.", domain: "Common Criteria" },
      { controlId: "CC6.2", title: "User Access Provisioning", description: "Prior to issuing credentials, verify the identity of the user and authorization.", domain: "Common Criteria" },
      { controlId: "CC6.3", title: "Access Removal and Adjustment", description: "Revoke or adjust access when users no longer require it or their roles change.", domain: "Common Criteria" },
      { controlId: "CC6.4", title: "Access Restrictions: Data and Programs", description: "Restrict physical access to prevent unauthorized removal of data or programs.", domain: "Common Criteria" },
      { controlId: "CC6.5", title: "Network and Data Segregation", description: "Restrict logical access to protect data from unauthorized modification or disclosure.", domain: "Common Criteria" },
      { controlId: "CC6.6", title: "Configuration Management", description: "Configure systems to prevent unauthorized access and detect unauthorized changes.", domain: "Common Criteria" },
      { controlId: "CC6.7", title: "User Access Management", description: "Restrict access to privileged functions and enforce least privilege.", domain: "Common Criteria" },
      { controlId: "CC6.8", title: "Application and Interface Access", description: "Prevent unauthorized information disclosure, damage, or destruction through applications and interfaces.", domain: "Common Criteria" },
      { controlId: "CC7.1", title: "Monitoring of Operations", description: "Monitor the operation of systems to detect deviations from expected operations.", domain: "Common Criteria" },
      { controlId: "CC7.2", title: "Incident Detection and Investigation", description: "Detect, investigate, and respond to security incidents to meet the security objective.", domain: "Common Criteria" },
      { controlId: "CC7.3", title: "Incident Response", description: "Establish response procedures to support timely response to security incidents.", domain: "Common Criteria" },
      { controlId: "CC7.4", title: "Incident Communication", description: "Communicate information about incidents and response to parties who may be affected.", domain: "Common Criteria" },
      { controlId: "CC8.1", title: "Change Management", description: "Authorize, design, develop, test, implement, and communicate changes.", domain: "Common Criteria" },
      { controlId: "CC9.1", title: "Risk Mitigation", description: "Identify, select, and develop risk mitigation activities for risks arising from potential business disruptions.", domain: "Common Criteria" },
      { controlId: "CC9.2", title: "Vendor and Business Partner Risk Management", description: "Assess, manage, and monitor risks from vendors and business partners.", domain: "Common Criteria" },
      { controlId: "A1.1", title: "Backups and Recovery", description: "Maintain, monitor, and test backup data and restore procedures.", domain: "Availability" },
      { controlId: "A1.2", title: "Capacity Management", description: "Manage capacity to meet availability commitments.", domain: "Availability" },
      { controlId: "A1.3", title: "Environment Protections", description: "Protect systems from environmental disruptions.", domain: "Availability" },
      { controlId: "C1.1", title: "Confidentiality Commitments", description: "Identify and maintain the confidential information the entity commits to protect.", domain: "Confidentiality" },
      { controlId: "C1.2", title: "Confidentiality Access and Disposal", description: "Restrict and dispose of confidential information in line with commitments.", domain: "Confidentiality" },
      { controlId: "PI1.1", title: "Processing Integrity Commitments", description: "Identify and communicate the entity's processing integrity commitments.", domain: "Processing Integrity" },
      { controlId: "PI1.2", title: "Processing Integrity: Complete and Accurate Processing", description: "Design systems to provide complete and accurate processing to meet commitments.", domain: "Processing Integrity" },
      { controlId: "PI1.3", title: "Processing Integrity: Resolve Errors", description: "Identify, communicate, and resolve processing errors in a timely manner.", domain: "Processing Integrity" },
      { controlId: "PI1.4", title: "Processing Integrity: Audit Trail", description: "Maintain sufficient audit trails to enable detection and investigation of errors.", domain: "Processing Integrity" },
      { controlId: "P1.1", title: "Privacy: Notice and Communication", description: "Provide notice to data subjects about privacy practices and commitments.", domain: "Privacy" },
      { controlId: "P1.2", title: "Privacy: Consent and Choice", description: "Obtain consent and provide choices consistent with stated privacy commitments.", domain: "Privacy" },
      { controlId: "P1.3", title: "Privacy: Collection and Use", description: "Collect and use personal information consistent with stated commitments.", domain: "Privacy" },
      { controlId: "P1.4", title: "Privacy: Access and Correction", description: "Provide data subjects access to their information and the ability to correct it.", domain: "Privacy" },
      { controlId: "P1.5", title: "Privacy: Disclosure and Retention", description: "Limit disclosures and retention of personal information consistent with commitments.", domain: "Privacy" },
    ],
  },
};
